{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData"]]},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/measurementdata\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/init","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@NixUniversalSDK@objc(cs)MeasurementData(im)init","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/init":{"title":"init","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/init","url":"\/documentation\/nixuniversalsdk\/measurementdata\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData":{"title":"MeasurementData","role":"symbol","abstract":[{"type":"text","text":"Class describing measurement data from a Nix device"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MeasurementData"}],"navigatorTitle":[{"kind":"identifier","text":"MeasurementData"}],"url":"\/documentation\/nixuniversalsdk\/measurementdata","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MeasurementData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/fragments","op":"replace","value":[{"text":"MeasurementData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/navigatorTitle","op":"replace","value":[{"text":"MeasurementData","kind":"identifier"}]}]}]}