{"metadata":{"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData(im)toColorDataForIlluminant:andObserver:andType:","role":"symbol","title":"toColorData(illuminant:observer:type:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier","text":"Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier","text":"Observer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","text":"ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":"?","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(illuminant:observer:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(illuminant:observer:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(illuminant:observer:type:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(toColorDataForIlluminant:andObserver:andType:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier","text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","text":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier","text":"IColorData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"kind":"text","text":"?"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"text":"Selected illuminant reference for output (defaults to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true,"type":"reference"},{"text":")","type":"text"}]}]},{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931"},{"type":"text","text":")"}]}]},{"name":"type","content":[{"inlineContent":[{"type":"text","text":"Output color type (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ"},{"type":"text","text":")"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(reference:type:)"}],"type":"paragraph"}]}]}]}],"kind":"symbol","abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if an invalid white point is specified.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","title":"ISpectralData","kind":"symbol","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"type":"topic","title":"Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"url":"\/documentation\/nixuniversalsdk\/illuminant","navigatorTitle":[{"kind":"identifier","text":"Illuminant"}],"abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/icolordata","title":"IColorData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toColorData(illuminant:observer:type:)":{"navigatorTitle":[{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(illuminant:observer:type:)","title":"toColorData(illuminant:observer:type:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(illuminant:observer:type:)","required":true,"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if an invalid white point is specified."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":"?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"type":"topic","abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":" objects. Values for each of these types can be freely converted to each other without loss of color data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorType"}],"title":"ColorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorType"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1931"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIE1931"}],"title":"Observer.CIE1931","kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"url":"\/documentation\/nixuniversalsdk\/illuminant\/d50","title":"Illuminant.D50","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D50"}],"navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","abstract":[{"type":"text","text":"Enum to describe the available options for reference observer"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Observer","kind":"identifier"}],"title":"Observer","url":"\/documentation\/nixuniversalsdk\/observer","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"role":"symbol","kind":"symbol","title":"ColorType.CIEXYZ","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","type":"topic","navigatorTitle":[{"text":"ColorTypeCIEXYZ","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIEXYZ","kind":"identifier"}],"abstract":[{"type":"text","text":"Report color value as CIEXYZ value on unity scale."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toColorData(reference:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(reference:type:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":"?","kind":"text"}],"required":true,"type":"topic","kind":"symbol","title":"toColorData(reference:type:)","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(reference:type:)","navigatorTitle":[{"text":"toColorDataForReference:andType:","kind":"identifier"}],"abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if an invalid white point is specified.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"toColorDataForIlluminant:andObserver:andType:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id<IColorData>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData"},{"text":") ","kind":"text"},{"text":"toColorDataForIlluminant:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":") ","kind":"text"},{"text":"illuminant","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"andObserver:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","text":"Observer"},{"kind":"text","text":") "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":" "},{"kind":"identifier","text":"andType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorType","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"illuminant","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","isActive":true},{"type":"text","text":")"}]}]},{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931"},{"type":"text","text":")"}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Output color type (defaults to "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","type":"reference"},{"type":"text","text":")"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"ISpectralData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"value":"Illuminant","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"},{"value":"IColorData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"value":[{"kind":"identifier","text":"IColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"},{"value":"toColorDataForIlluminant:andObserver:andType:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(illuminant:observer:type:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(illuminant:observer:type:)\/fragments"},{"value":"ColorType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"value":[{"kind":"identifier","text":"ColorType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments"},{"value":[{"text":"ColorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle"},{"value":"ObserverCIE1931","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title"},{"value":[{"kind":"identifier","text":"ObserverCIE1931"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments"},{"value":"IlluminantD50","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title"},{"value":[{"kind":"identifier","text":"IlluminantD50"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"},{"value":"Observer","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title"},{"value":[{"kind":"identifier","text":"Observer"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments"},{"value":[{"text":"Observer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle"},{"value":"ColorTypeCIEXYZ","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title"},{"value":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments"},{"value":"toColorDataForReference:andType:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(reference:type:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(reference:type:)\/fragments"}]}]}