{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"USB_CDC","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/usb_cdc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/interfacetype\/usb_cdc"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/USB_CDC"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"USB_CDC","kind":"identifier"}],"title":"InterfaceType.USB_CDC","navigatorTitle":[{"text":"InterfaceTypeUSB_CDC","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@NixUniversalSDK@E@InterfaceType@InterfaceTypeUSB_CDC","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType"]]},"abstract":[{"type":"text","text":"Device connects via USB interface."}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/USB_CDC":{"title":"InterfaceType.USB_CDC","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/interfacetype\/usb_cdc","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/USB_CDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"USB_CDC"}],"navigatorTitle":[{"kind":"identifier","text":"InterfaceTypeUSB_CDC"}],"abstract":[{"type":"text","text":"Device connects via USB interface."}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}],"navigatorTitle":[{"kind":"identifier","text":"InterfaceType"}],"title":"InterfaceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","url":"\/documentation\/nixuniversalsdk\/interfacetype","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"InterfaceTypeUSB_CDC","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"InterfaceTypeUSB_CDC","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"InterfaceTypeUSB_CDC","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"InterfaceTypeUSB_CDC","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1USB_CDC\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1USB_CDC\/fragments","op":"replace","value":[{"text":"InterfaceTypeUSB_CDC","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title","op":"replace","value":"InterfaceType"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments","op":"replace","value":[{"text":"InterfaceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"InterfaceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}