{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_DROPPED_CONNECTION"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceStatus@DeviceStatusERROR_DROPPED_CONNECTION","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_DROPPED_CONNECTION","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceStatusERROR_DROPPED_CONNECTION","kind":"identifier"}],"title":"DeviceStatus.ERROR_DROPPED_CONNECTION","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_dropped_connection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_dropped_connection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ERROR_DROPPED_CONNECTION","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus"]]},"abstract":[{"type":"text","text":"The device has disconnected unexpectedly (possibly due to low Bluetooth signal strength or low battery level)."}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"url":"\/documentation\/nixuniversalsdk\/devicestatus","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","role":"symbol","title":"DeviceStatus","abstract":[{"text":"Enum describing the possible causes of a device disconnection event in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DeviceStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_DROPPED_CONNECTION":{"navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_DROPPED_CONNECTION","url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_dropped_connection","type":"topic","title":"DeviceStatus.ERROR_DROPPED_CONNECTION","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_DROPPED_CONNECTION"}],"role":"symbol","abstract":[{"type":"text","text":"The device has disconnected unexpectedly (possibly due to low Bluetooth signal strength or low battery level)."}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","navigatorTitle":[{"kind":"identifier","text":"DeviceStateDelegate"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Definition for a callback from an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStateDelegate"}],"title":"DeviceStateDelegate","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DeviceStatusERROR_DROPPED_CONNECTION","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DeviceStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceStatus"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceStatus"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_DROPPED_CONNECTION\/title","op":"replace","value":"DeviceStatusERROR_DROPPED_CONNECTION"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_DROPPED_CONNECTION\/fragments","op":"replace","value":[{"kind":"identifier","text":"DeviceStatusERROR_DROPPED_CONNECTION"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","op":"replace","value":"DeviceStateDelegate"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","op":"replace","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","op":"replace","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]}]}]}