{"kind":"symbol","metadata":{"externalID":"c:@M@NixUniversalSDK@E@DeviceStatus@DeviceStatusERROR_MAX_ATTEMPTS","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_MAX_ATTEMPTS"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}],"roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"title":"DeviceStatus.ERROR_MAX_ATTEMPTS"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"The device connection attempt was cancelled because the maximum number of attempts was reached."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_MAX_ATTEMPTS","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_max_attempts"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_max_attempts"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_MAX_ATTEMPTS"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"title":"DeviceStateDelegate","navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","abstract":[{"text":"Definition for a callback from an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"role":"symbol","abstract":[{"text":"Enum describing the possible causes of a device disconnection event in the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","type":"reference"},{"text":".","type":"text"}],"type":"topic","title":"DeviceStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStatus","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicestatus","navigatorTitle":[{"text":"DeviceStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_MAX_ATTEMPTS":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_MAX_ATTEMPTS","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_MAX_ATTEMPTS"}],"abstract":[{"text":"The device connection attempt was cancelled because the maximum number of attempts was reached.","type":"text"}],"type":"topic","title":"DeviceStatus.ERROR_MAX_ATTEMPTS","url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_max_attempts"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DeviceStatusERROR_MAX_ATTEMPTS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DeviceStatusERROR_MAX_ATTEMPTS"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title","value":"DeviceStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments","value":[{"text":"DeviceStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_MAX_ATTEMPTS\/title","value":"DeviceStatusERROR_MAX_ATTEMPTS"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_MAX_ATTEMPTS\/fragments","value":[{"text":"DeviceStatusERROR_MAX_ATTEMPTS","kind":"identifier"}]}]}]}