{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"DeviceType.SPECTRO2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SPECTRO2","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceType@DeviceTypeSPECTRO2","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceTypeSPECTRO2"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/spectro2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicetype\/spectro2"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"]]},"kind":"symbol","abstract":[{"text":"Type for Nix Spectro 2 spectrophotometer","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SPECTRO2"}],"platforms":["macOS"]}]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/SPECTRO2":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SPECTRO2"}],"title":"DeviceType.SPECTRO2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/SPECTRO2","navigatorTitle":[{"kind":"identifier","text":"DeviceTypeSPECTRO2"}],"role":"symbol","abstract":[{"text":"Type for Nix Spectro 2 spectrophotometer","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/devicetype\/spectro2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","title":"DeviceType","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"url":"\/documentation\/nixuniversalsdk\/devicetype","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DeviceTypeSPECTRO2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"DeviceTypeSPECTRO2"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/title","op":"replace","value":"DeviceTypeSPECTRO2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType~1SPECTRO2\/fragments","op":"replace","value":[{"text":"DeviceTypeSPECTRO2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","op":"replace","value":"DeviceType"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments","value":[{"text":"DeviceType","kind":"identifier"}]},{"op":"replace","value":[{"text":"DeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}