{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromString(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Helper to find a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"type":"text","text":" enum from a "},{"code":"String","type":"codeVoice"},{"type":"text","text":" value, or "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","isActive":true},{"type":"text","text":" for invalid input."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Type Method","title":"fromString(_:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","externalID":"s:15NixUniversalSDK8ScanModeO10fromStringyACSSSgFZ"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/scanmode\/fromstring(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/NA":{"role":"symbol","abstract":[{"type":"text","text":"Unknown \/ undefined conditions"}],"kind":"symbol","type":"topic","title":"ScanMode.NA","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NA"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","navigatorTitle":[{"kind":"identifier","text":"ScanModeNA"}],"url":"\/documentation\/nixuniversalsdk\/scanmode\/na"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/fromString(_:)":{"role":"symbol","kind":"symbol","title":"fromString(_:)","url":"\/documentation\/nixuniversalsdk\/scanmode\/fromstring(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/fromString(_:)","abstract":[{"text":"Helper to find a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"text":" enum from a ","type":"text"},{"type":"codeVoice","code":"String"},{"text":" value, or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/NA","isActive":true},{"text":" for invalid input.","type":"text"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","title":"ScanMode","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/scanmode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanMode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/title","op":"replace","value":"ScanModeNA"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode~1NA\/fragments","op":"replace","value":[{"kind":"identifier","text":"ScanModeNA"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace","value":"ScanMode"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","op":"replace","value":[{"text":"ScanMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","op":"replace","value":[{"text":"ScanMode","kind":"identifier"}]}]}]}