{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/scanmode\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/RawRepresentable-Implementations"]]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/hashValue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Property","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hashValue","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@NixUniversalSDK@E@ScanMode","extendedModule":"Swift","symbolKind":"property","modules":[{"relatedModules":["Swift"],"name":"NixUniversalSDK"}]},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/hashValue":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"url":"\/documentation\/nixuniversalsdk\/scanmode\/hashvalue","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/hashValue","kind":"symbol","title":"hashValue"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","type":"topic","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}],"title":"ScanMode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/scanmode"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/nixuniversalsdk\/scanmode\/rawrepresentable-implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"kind":"identifier","text":"ScanMode"}]},{"value":[{"kind":"identifier","text":"ScanMode"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}