{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onExtPowerStateChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"sender","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sender","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device instance that has invoked this call"}]}]},{"name":"newState","content":[{"inlineContent":[{"type":"text","text":"New external power connection state"}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"]]},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"text","text":"- "},{"text":"onExtPowerStateChanged:newState:","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"method","required":true,"role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)DeviceStateDelegate(im)onExtPowerStateChanged:newState:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onExtPowerStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"newState","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"onExtPowerStateChanged(_:newState:)"},"sections":[],"abstract":[{"text":"Called when the Nix device has been connected or disconnected from an external power source.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate\/onextpowerstatechanged(_:newstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/devicestatedelegate\/onextpowerstatechanged(_:newstate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onExtPowerStateChanged(_:newState:)","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onExtPowerStateChanged(_:newState:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onExtPowerStateChanged(_:newState:)","type":"topic","title":"onExtPowerStateChanged(_:newState:)","abstract":[{"text":"Called when the Nix device has been connected or disconnected from an external power source.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onExtPowerStateChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","kind":"typeIdentifier","text":"IDeviceCompat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newState"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onExtPowerStateChanged:newState:"}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onextpowerstatechanged(_:newstate:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","navigatorTitle":[{"kind":"identifier","text":"DeviceStateDelegate"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Definition for a callback from an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStateDelegate"}],"title":"DeviceStateDelegate","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","type":"topic","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onExtPowerStateChanged:newState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onExtPowerStateChanged:newState:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onExtPowerStateChanged:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"id<IDeviceCompat>"},{"kind":"text","text":") "},{"text":"sender","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"newState:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"newState","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device instance that has invoked this call"}]}],"name":"sender"},{"content":[{"type":"paragraph","inlineContent":[{"text":"New external power connection state","type":"text"}]}],"name":"newState"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onExtPowerStateChanged(_:newState:)\/title","value":"onExtPowerStateChanged:newState:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onExtPowerStateChanged(_:newState:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onExtPowerStateChanged:newState:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DeviceStateDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"kind":"identifier","text":"DeviceScanner"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","value":[{"text":"DeviceScanner","kind":"identifier"}],"op":"replace"}]}]}