{"metadata":{"roleHeading":"Case","externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteD75_10","role":"symbol","title":"ReferenceWhite.D75_10","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD75_10"}],"modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D75_10"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"D75_10","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"sections":[],"abstract":[{"type":"text","text":"White point using Illuminant D75 and 10 degree observer."}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d75_10"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d75_10"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_10","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"title":"ReferenceWhite","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D75_10":{"abstract":[{"type":"text","text":"White point using Illuminant D75 and 10 degree observer."}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d75_10","navigatorTitle":[{"text":"ReferenceWhiteD75_10","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ReferenceWhite.D75_10","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D75_10"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D75_10"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"ReferenceWhiteD75_10","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ReferenceWhiteD75_10"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ReferenceWhiteD75_10","kind":"identifier"}],"platforms":["macOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"},{"op":"replace","value":[{"text":"ReferenceWhite","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_10\/title","op":"replace","value":"ReferenceWhiteD75_10"},{"op":"replace","value":[{"kind":"identifier","text":"ReferenceWhiteD75_10"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D75_10\/fragments"}]}]}