{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_10"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteF7_10","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"F7_10"}],"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF7_10"}],"title":"ReferenceWhite.F7_10","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f7_10"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f7_10"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"F7_10"}],"platforms":["macOS"]}]},{"mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"],"kind":"mentions"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"abstract":[{"text":"White point using Illuminant F7 and 10 degree observer.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F7_10":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_10","type":"topic","title":"ReferenceWhite.F7_10","abstract":[{"type":"text","text":"White point using Illuminant F7 and 10 degree observer."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"F7_10"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF7_10"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/f7_10"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"type":"topic","title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ReferenceWhiteF7_10","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ReferenceWhiteF7_10","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ReferenceWhiteF7_10"}],"platforms":["macOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ReferenceWhiteF7_10","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_10\/title"},{"op":"replace","value":[{"text":"ReferenceWhiteF7_10","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_10\/fragments"},{"op":"replace","value":"ReferenceWhite","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"text":"ReferenceWhite","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"text":"ReferenceWhite","kind":"identifier"}]}]}]}