{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_2","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","title":"ReferenceWhite.F7_2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"F7_2","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteF7_2","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteF7_2"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f7_2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/f7_2"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"kind":"symbol","abstract":[{"text":"White point using Illuminant F7 and 2 degree observer.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"F7_2","kind":"identifier"}],"platforms":["macOS"]}],"kind":"declarations"},{"mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"],"kind":"mentions"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"type":"topic","title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/F7_2":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"F7_2","kind":"identifier"}],"title":"ReferenceWhite.F7_2","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/F7_2","navigatorTitle":[{"text":"ReferenceWhiteF7_2","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"White point using Illuminant F7 and 2 degree observer.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/referencewhite\/f7_2"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ReferenceWhiteF7_2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ReferenceWhiteF7_2","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ReferenceWhiteF7_2"}]}]}},{"value":"ReferenceWhite","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title"},{"value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_2\/title","op":"replace","value":"ReferenceWhiteF7_2"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1F7_2\/fragments","op":"replace","value":[{"text":"ReferenceWhiteF7_2","kind":"identifier"}]}]}]}