{"abstract":[{"text":"Provides access to basic device information and colorimetry values via ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"type":"text","text":" for all Nix devices."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BASIC_DATA"}],"platforms":["macOS"]}]}],"metadata":{"roleHeading":"Case","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"LicenseFeatureBASIC_DATA","kind":"identifier"}],"title":"LicenseFeature.BASIC_DATA","role":"symbol","externalID":"c:@M@NixUniversalSDK@E@LicenseFeature@LicenseFeatureBASIC_DATA","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BASIC_DATA"}],"symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensefeature\/basic_data"]},{"paths":["\/documentation\/nixuniversalsdk\/licensefeature\/basic_data"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/BASIC_DATA","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","title":"IColorData","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IColorData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"url":"\/documentation\/nixuniversalsdk\/licensemanager","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","title":"LicenseManager","type":"topic","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","type":"topic","abstract":[{"type":"text","text":"Helper to check if a particular "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference"},{"type":"text","text":" is enabled by the current license."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFeatureEnabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"LicenseFeature","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFeatureEnabled:","kind":"identifier"}],"kind":"symbol","title":"isFeatureEnabled(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"role":"symbol","title":"LicenseFeature","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"type":"text","text":". Feature availability can be queried using "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","type":"reference"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature/BASIC_DATA":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseFeatureBASIC_DATA"}],"abstract":[{"type":"text","text":"Provides access to basic device information and colorimetry values via "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"type":"text","text":" for all Nix devices."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"BASIC_DATA","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/BASIC_DATA","title":"LicenseFeature.BASIC_DATA","url":"\/documentation\/nixuniversalsdk\/licensefeature\/basic_data","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"LicenseFeatureBASIC_DATA","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LicenseFeatureBASIC_DATA"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"LicenseFeatureBASIC_DATA"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","value":[{"kind":"identifier","text":"IColorData"}]},{"value":[{"kind":"identifier","text":"IColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"},{"value":"LicenseManager","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}]},{"op":"replace","value":[{"kind":"identifier","text":"LicenseManager"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle"},{"op":"replace","value":"isFeatureEnabled:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isFeatureEnabled:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title","value":"LicenseFeature"},{"value":[{"kind":"identifier","text":"LicenseFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","value":[{"kind":"identifier","text":"LicenseFeature"}],"op":"replace"},{"op":"replace","value":"LicenseFeatureBASIC_DATA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1BASIC_DATA\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeatureBASIC_DATA"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1BASIC_DATA\/fragments"}]}]}