{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IDeviceScanner","kind":"typeIdentifier","text":"id<IDeviceScanner>"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScannerNonnull"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"metadata":{"roleHeading":"Type Alias","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerNonnull"}],"symbolKind":"typealias","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","externalID":"c:TypeAliases.h@T@DeviceScannerNonnull","fragments":[{"text":"DeviceScannerNonnull","kind":"identifier"}],"title":"DeviceScannerNonnull"},"sections":[],"abstract":[{"type":"text","text":"Non-null instance of an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"},{"type":"text","text":" object"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicescannernonnull"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNonnull","interfaceLanguage":"occ"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","type":"topic","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerNonnull":{"fragments":[{"kind":"identifier","text":"DeviceScannerNonnull"}],"title":"DeviceScannerNonnull","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNonnull","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-null instance of an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","type":"reference","isActive":true},{"type":"text","text":" object"}],"url":"\/documentation\/nixuniversalsdk\/devicescannernonnull"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","role":"symbol","title":"IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceScanner","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"IDeviceScanner","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"op":"replace","value":"IDeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title"},{"op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments"},{"value":[{"text":"IDeviceScanner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}