{"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/compareTo(other:type:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/icolordata\/compareto(other:type:)"]},{"paths":["\/documentation\/nixuniversalsdk\/icolordata\/compareto(other:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"compareToOther:type:","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"required":true,"roleHeading":"Instance Method","title":"compareTo(other:type:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","text":"ColorDifferenceType"},{"text":") -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IColorData(im)compareToOther:type:"},"abstract":[{"text":"Calculate delta E between this color and another. The colors must share the same reference white point (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference"},{"text":").","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compareTo"},{"text":"(","kind":"text"},{"text":"other","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IColorData","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","text":"ColorDifferenceType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"other","content":[{"inlineContent":[{"text":"Another ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","type":"reference","isActive":true},{"type":"text","text":" instance"}],"type":"paragraph"}]},{"name":"type","content":[{"inlineContent":[{"type":"text","text":"Delta E equation type (defaults to CIE2000)"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"title":"ColorDifferenceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorDifferenceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceType"}],"abstract":[{"type":"text","text":"Enum describing the available color difference (delta E) equations."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colordifferencetype"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/compareTo(other:type:)":{"title":"compareTo(other:type:)","abstract":[{"type":"text","text":"Calculate delta E between this color and another. The colors must share the same reference white point ("},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","isActive":true,"type":"reference"},{"text":").","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"text":"other","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ColorDifferenceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"compareToOther:type:"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/icolordata\/compareto(other:type:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/compareTo(other:type:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData/reference":{"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/icolordata\/reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData\/reference","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"reference","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Reference white point for this color value."}],"type":"topic","title":"reference","navigatorTitle":[{"text":"reference","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","title":"IColorData","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IColorData"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"compareToOther:type:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"compareToOther:type:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"identifier","text":"compareToOther:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","text":"id<IColorData>"},{"text":") ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ColorDifferenceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Another "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":" instance","type":"text"}]}],"name":"other"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delta E equation type (defaults to CIE2000)"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title","value":"ColorDifferenceType"},{"value":[{"text":"ColorDifferenceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","value":[{"text":"ColorDifferenceType","kind":"identifier"}]},{"value":"compareToOther:type:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1compareTo(other:type:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"compareToOther:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1compareTo(other:type:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/title","value":"reference","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData~1reference\/fragments","value":[{"kind":"identifier","text":"reference"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","op":"replace","value":"IColorData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"}]}]}