{"metadata":{"role":"symbol","required":true,"symbolKind":"method","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(im)providesColorForReference:","navigatorTitle":[{"kind":"identifier","text":"providesColorForReference:"}],"title":"providesColor(reference:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"providesColor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(providesColorForReference:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"providesColor","kind":"identifier"},{"kind":"text","text":"("},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["macOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(reference:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providescolor(reference:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providescolor(reference:)"]}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if color data for the selected combination of illuminant and observer are available for this measurement."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"kind":"symbol","abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","title":"IMeasurementData","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesColor(reference:)":{"type":"topic","abstract":[{"type":"text","text":"Returns "},{"code":"true","type":"codeVoice"},{"text":" if color data for the selected combination of illuminant and observer are available for this measurement.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesColor(reference:)","navigatorTitle":[{"kind":"identifier","text":"providesColorForReference:"}],"title":"providesColor(reference:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providesColor"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providescolor(reference:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance."}],"title":"DeviceResultCallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceResultCallback"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"title":"ReferenceWhite","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"abstract":[{"type":"text","text":"Reconstructs a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference"},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the data is invalid."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","title":"fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromRaw"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"title":"IDeviceCompat","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"providesColorForReference:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"providesColorForReference:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"providesColorForReference:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"},{"kind":"text","text":") "},{"kind":"internalParam","text":"reference"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","op":"replace","value":"IMeasurementData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"kind":"identifier","text":"IMeasurementData"}]},{"value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle"},{"value":"providesColorForReference:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(reference:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesColor(reference:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"providesColorForReference:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","op":"replace","value":"ReferenceWhite"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ReferenceWhite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}