{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"abstract":[{"type":"text","text":"Flag (as a "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" wrapped "},{"code":"Bool","type":"codeVoice"},{"type":"text","text":") indicating if this measurement provides spectral values. This value depends on both the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","type":"reference","isActive":true},{"type":"text","text":" and availability of the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA","type":"reference","isActive":true},{"type":"text","text":" feature."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providesSpectral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/isFeatureSupported(_:)","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See also: "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","type":"reference","isActive":true}]}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providesspectral"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/providesspectral"]}],"metadata":{"navigatorTitle":[{"text":"providesSpectral","kind":"identifier"}],"title":"providesSpectral","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(py)providesSpectral","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providesSpectral","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","required":true},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesSpectral"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Reconstructs a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the data is invalid."}],"type":"topic","title":"fromRaw(_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFeatureEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","text":"LicenseFeature"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isFeatureEnabled(_:)","navigatorTitle":[{"kind":"identifier","text":"isFeatureEnabled:"}],"abstract":[{"type":"text","text":"Helper to check if a particular "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"reference","isActive":true},{"type":"text","text":" is enabled by the current license."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"navigatorTitle":[{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseFeature"}],"type":"topic","role":"symbol","kind":"symbol","title":"LicenseFeature","abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true},{"type":"text","text":". Feature availability can be queried using "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","isActive":true},{"type":"text","text":"."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","kind":"symbol","title":"DeviceResultCallback","type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"abstract":[{"text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature/SPECTRAL_DATA":{"url":"\/documentation\/nixuniversalsdk\/licensefeature\/spectral_data","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SPECTRAL_DATA"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseFeatureSPECTRAL_DATA"}],"title":"LicenseFeature.SPECTRAL_DATA","abstract":[{"type":"text","text":"Provides access to spectral values via "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","isActive":true},{"type":"text","text":", if supported by the Nix device."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","title":"ISpectralData","kind":"symbol","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType/isFeatureSupported(_:)":{"title":"isFeatureSupported(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFeatureSupported","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LicenseFeature","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicetype\/isfeaturesupported(_:)","role":"symbol","abstract":[{"text":"Defines if a particular feature is supported by a certain device type","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType\/isFeatureSupported(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/deviceType":{"abstract":[{"type":"text","text":"Device type that was used to make this measurement."}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/devicetype","kind":"symbol","navigatorTitle":[{"text":"deviceType","kind":"identifier"}],"title":"deviceType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType","kind":"typeIdentifier"}],"required":true,"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/providesSpectral":{"url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/providesspectral","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providesSpectral","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"}],"abstract":[{"text":"Flag (as a ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"text":" wrapped ","type":"text"},{"code":"Bool","type":"codeVoice"},{"text":") indicating if this measurement provides spectral values. This value depends on both the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/deviceType","isActive":true,"type":"reference"},{"text":" and availability of the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature\/SPECTRAL_DATA","isActive":true,"type":"reference"},{"text":" feature.","type":"text"}],"required":true,"navigatorTitle":[{"text":"providesSpectral","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/providesSpectral","title":"providesSpectral","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IMeasurementData","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"title":"IMeasurementData","url":"\/documentation\/nixuniversalsdk\/imeasurementdata","type":"topic","abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},{"type":"text","text":"."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"providesSpectral","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"providesSpectral","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"providesSpectral"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isFeatureEnabled:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isFeatureEnabled:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments"},{"op":"replace","value":"LicenseFeature","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"op":"replace","value":[{"text":"LicenseFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle"},{"op":"replace","value":"IDeviceCompat","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","value":"LicenseFeatureSPECTRAL_DATA","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/title"},{"op":"replace","value":[{"text":"LicenseFeatureSPECTRAL_DATA","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature~1SPECTRAL_DATA\/fragments"},{"op":"replace","value":"ISpectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title"},{"op":"replace","value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"op":"replace","value":[{"text":"ISpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"op":"replace","value":"deviceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1deviceType\/title"},{"op":"replace","value":[{"text":"deviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1deviceType\/fragments"},{"op":"replace","value":"providesSpectral","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesSpectral\/title"},{"op":"replace","value":[{"kind":"identifier","text":"providesSpectral"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1providesSpectral\/fragments"},{"op":"replace","value":"IMeasurementData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title"},{"op":"replace","value":[{"text":"IMeasurementData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments"},{"value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle"}]}]}