{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"title":"toColorData(illuminant:observer:type:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":"?"}],"externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(im)toColorDataForIlluminant:andObserver:andType:","roleHeading":"Instance Method","required":true,"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(toColorDataForIlluminant:andObserver:andType:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]},{"parameters":[{"name":"illuminant","content":[{"inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","type":"reference","isActive":true},{"text":")","type":"text"}],"type":"paragraph"}]},{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"Selected observer reference for output (defaults to ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","isActive":true},{"text":")","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Output color type (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ"},{"type":"text","text":")"}]}],"name":"type"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","isActive":true}]}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"sections":[],"abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(illuminant:observer:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(illuminant:observer:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"title":"ColorType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorType"}],"url":"\/documentation\/nixuniversalsdk\/colortype","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorType"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"title":"Observer.CIE1931","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1931"}],"abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIE1931","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance."}],"title":"DeviceResultCallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceResultCallback"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(reference:type:)":{"type":"topic","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(reference:type:)","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"required":true,"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"toColorDataForReference:andType:"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(reference:type:)","title":"toColorData(reference:type:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"abstract":[{"type":"text","text":"Reconstructs a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference"},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the data is invalid."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","title":"fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromRaw"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"kind":"symbol","abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","title":"IMeasurementData","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"abstract":[],"title":"Illuminant.D50","url":"\/documentation\/nixuniversalsdk\/illuminant\/d50"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toColorData(illuminant:observer:type:)":{"title":"toColorData(illuminant:observer:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"kind":"text","text":"("},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/tocolordata(illuminant:observer:type:)","required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toColorData(illuminant:observer:type:)","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIEXYZ":{"abstract":[{"type":"text","text":"Report color value as CIEXYZ value on unity scale."}],"title":"ColorType.CIEXYZ","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIEXYZ"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","type":"topic","url":"\/documentation\/nixuniversalsdk\/colortype\/ciexyz","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"title":"IDeviceCompat","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","title":"IColorData","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IColorData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"title":"Illuminant","role":"symbol","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Observer"}],"role":"symbol","abstract":[{"text":"Enum to describe the available options for reference observer","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","title":"Observer","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/observer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"toColorDataForIlluminant:andObserver:andType:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id<IColorData>","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"toColorDataForIlluminant:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"illuminant"},{"text":" ","kind":"text"},{"text":"andObserver:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"observer"},{"kind":"text","text":" "},{"text":"andType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","text":"ColorType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","type":"reference"},{"text":")","type":"text"}]}],"name":"illuminant"},{"name":"observer","content":[{"inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","isActive":true,"type":"reference"},{"type":"text","text":")"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Output color type (defaults to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIEXYZ","isActive":true},{"type":"text","text":")"}],"type":"paragraph"}],"name":"type"}]},"op":"replace"},{"op":"replace","value":"ColorType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"kind":"identifier","text":"ColorType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"text":"ColorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","value":"ObserverCIE1931"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments","value":[{"kind":"identifier","text":"ObserverCIE1931"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/title","op":"replace","value":"toColorDataForReference:andType:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(reference:type:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toColorDataForReference:andType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","op":"replace","value":"IMeasurementData"},{"value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","op":"replace","value":[{"text":"IMeasurementData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","value":"IlluminantD50","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments","value":[{"text":"IlluminantD50","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/title","value":"toColorDataForIlluminant:andObserver:andType:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toColorData(illuminant:observer:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}]},{"value":"ColorTypeCIEXYZ","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/title"},{"value":[{"kind":"identifier","text":"ColorTypeCIEXYZ"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIEXYZ\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"op":"replace","value":"IColorData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title"},{"value":[{"kind":"identifier","text":"IColorData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"op":"replace","value":[{"text":"IColorData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title","op":"replace","value":"Illuminant"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments","value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"kind":"identifier","text":"Observer"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","op":"replace","value":[{"text":"Observer","kind":"identifier"}]}]}]}