{"variants":[{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(illuminant:observer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(illuminant:observer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(toRgbValueForIlluminant:andObserver:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","text":"Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Observer","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":">?"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Selected illuminant reference for output (defaults to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50"},{"type":"text","text":")"}],"type":"paragraph"}],"name":"illuminant"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected observer reference for output (defaults to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","isActive":true,"type":"reference"},{"text":")","type":"text"}]}],"name":"observer"}],"kind":"parameters"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"See also ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(reference:)"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(illuminant:observer:)"},"metadata":{"symbolKind":"method","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData(im)toRgbValueForIlluminant:andObserver:","title":"toRgbValue(illuminant:observer:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"navigatorTitle":[{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"required":true},"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toRgbValue(reference:)":{"kind":"symbol","navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?","kind":"text"}],"title":"toRgbValue(reference:)","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(reference:)","type":"topic","required":true,"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(reference:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer/CIE1931":{"title":"Observer.CIE1931","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObserverCIE1931"}],"abstract":[{"type":"text","text":"Observer defined by CIE1931 (2 degree)"}],"url":"\/documentation\/nixuniversalsdk\/observer\/cie1931","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"CIE1931","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Observer"}],"role":"symbol","abstract":[{"text":"Enum to describe the available options for reference observer","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","title":"Observer","navigatorTitle":[{"kind":"identifier","text":"Observer"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/observer","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"title":"IDeviceCompat","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance."}],"title":"DeviceResultCallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceResultCallback"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData/toRgbValue(illuminant:observer:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"},{"text":") -> ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"title":"toRgbValue(illuminant:observer:)","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/imeasurementdata\/torgbvalue(illuminant:observer:)","abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"navigatorTitle":[{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData\/toRgbValue(illuminant:observer:)","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"kind":"symbol","abstract":[{"text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","title":"IMeasurementData","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMeasurementData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"abstract":[{"type":"text","text":"Reconstructs a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"reference"},{"type":"text","text":" instance from its raw string value, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the data is invalid."}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","title":"fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromRaw"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"title":"Illuminant","role":"symbol","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/illuminant"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/D50":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50"}],"navigatorTitle":[{"kind":"identifier","text":"IlluminantD50"}],"abstract":[],"title":"Illuminant.D50","url":"\/documentation\/nixuniversalsdk\/illuminant\/d50"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"toRgbValueForIlluminant:andObserver:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"toRgbValueForIlluminant:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"text":") ","kind":"text"},{"text":"illuminant","kind":"internalParam"},{"kind":"text","text":" "},{"text":"andObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"kind":"text","text":") "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Selected illuminant reference for output (defaults to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/D50","type":"reference","isActive":true},{"type":"text","text":")"}],"type":"paragraph"}],"name":"illuminant"},{"name":"observer","content":[{"type":"paragraph","inlineContent":[{"text":"Selected observer reference for output (defaults to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer\/CIE1931","type":"reference","isActive":true},{"text":")","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"toRgbValueForReference:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(reference:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForReference:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(reference:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/title","value":"ObserverCIE1931","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer~1CIE1931\/fragments","value":[{"kind":"identifier","text":"ObserverCIE1931"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","value":"Observer"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","value":[{"text":"Observer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","op":"replace","value":[{"text":"Observer","kind":"identifier"}]},{"value":"IDeviceCompat","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","value":"toRgbValueForIlluminant:andObserver:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(illuminant:observer:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData~1toRgbValue(illuminant:observer:)\/fragments"},{"value":"IMeasurementData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title"},{"value":[{"kind":"identifier","text":"IMeasurementData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","op":"replace"},{"op":"replace","value":[{"text":"IMeasurementData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle"},{"value":"Illuminant","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"op":"replace","value":[{"text":"Illuminant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"value":[{"kind":"identifier","text":"Illuminant"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/title","op":"replace","value":"IlluminantD50"},{"value":[{"text":"IlluminantD50","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant~1D50\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}