{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary\/scanModeMap"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"NixUniversalSDK","relatedModules":["Swift"]}],"title":"scanModeMap","externalID":"s:SD15NixUniversalSDKSo8NSNumberCRszAA16IMeasurementData_pRs_rlE11scanModeMapSDyAA04ScanH0OAaD_pGvp","conformance":{"constraints":[{"type":"codeVoice","code":"Key"},{"type":"text","text":" is "},{"type":"codeVoice","code":"NSNumber"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Value"},{"type":"text","text":" is "},{"type":"codeVoice","code":"any IMeasurementData"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scanModeMap"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier","text":"ScanMode"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","kind":"typeIdentifier","text":"IMeasurementData"},{"kind":"text","text":"]"}],"extendedModule":"Swift"},"sections":[],"abstract":[{"type":"text","text":"Dictionary with "},{"code":"NSNumber","type":"codeVoice"},{"type":"text","text":" keys unwrapped into "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true},{"type":"text","text":" keys"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanModeMap","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/swift\/dictionary\/scanmodemap"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromRaw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Reconstructs a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the data is invalid."}],"type":"topic","title":"fromRaw(_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift":{"abstract":[],"title":"Swift","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift","type":"topic","role":"collection","url":"\/documentation\/nixuniversalsdk\/swift","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","title":"ScanMode","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the measurement modes used by Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/scanmode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ScanMode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanMode"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift/Dictionary":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary","title":"Dictionary","role":"symbol","url":"\/documentation\/nixuniversalsdk\/swift\/dictionary","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"Dictionary"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IMeasurementData","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"title":"IMeasurementData","url":"\/documentation\/nixuniversalsdk\/imeasurementdata","type":"topic","abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" instance, or can be reconstructed from raw string data using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift/Dictionary/scanModeMap":{"role":"symbol","abstract":[{"text":"Dictionary with ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"text":" keys unwrapped into ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","isActive":true,"type":"reference"},{"text":" keys","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scanModeMap","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData","text":"IMeasurementData","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/nixuniversalsdk\/swift\/dictionary\/scanmodemap","type":"topic","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Key","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"NSNumber","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"Value","type":"codeVoice"},{"text":" is ","type":"text"},{"code":"any IMeasurementData","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"title":"scanModeMap","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift\/Dictionary\/scanModeMap"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"role":"symbol","kind":"symbol","title":"DeviceResultCallback","type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback","navigatorTitle":[{"text":"DeviceResultCallback","kind":"identifier"}],"abstract":[{"text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","value":"ScanMode"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","value":[{"text":"ScanMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","value":[{"kind":"identifier","text":"ScanMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title","value":"IMeasurementData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments","value":[{"kind":"identifier","text":"IMeasurementData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","value":[{"kind":"identifier","text":"IMeasurementData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","value":"IDeviceCompat"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"text":"IDeviceCompat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","value":[{"kind":"identifier","text":"IDeviceCompat"}]}]}]}