{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant"]]},"kind":"article","topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/!=(_:_:)"]}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/illuminant\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/nixuniversalsdk\/illuminant\/!=(_:_:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"abstract":[{"type":"text","text":"Enum to describe the available options for reference illuminant"}],"title":"Illuminant","role":"symbol","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Illuminant"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/illuminant"}},"variantOverrides":[{"patch":[{"value":"Illuminant","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle","value":[{"kind":"identifier","text":"Illuminant"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}