{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIELCH"}],"platforms":["macOS"]}],"kind":"declarations"},{"mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"],"kind":"mentions"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"ColorTypeCIELCH","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@E@ColorType@ColorTypeCIELCH","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIELCH"}],"title":"ColorType.CIELCH"},"sections":[],"abstract":[{"text":"Report color value as CIELCH \/ LCH(ab) value","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colortype\/cielch"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colortype\/cielch"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELCH"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType/CIELCH":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIELCH","kind":"identifier"}],"title":"ColorType.CIELCH","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType\/CIELCH","navigatorTitle":[{"text":"ColorTypeCIELCH","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Report color value as CIELCH \/ LCH(ab) value","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colortype\/cielch"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","title":"ColorType","abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"url":"\/documentation\/nixuniversalsdk\/colortype","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","abstract":[{"text":"Protocol describing colorimetry data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/icolordata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"type":"topic","title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ColorTypeCIELCH"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ColorTypeCIELCH","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ColorTypeCIELCH"}]}],"kind":"declarations"}},{"value":"ColorTypeCIELCH","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELCH\/title"},{"value":[{"kind":"identifier","text":"ColorTypeCIELCH"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType~1CIELCH\/fragments"},{"value":"ColorType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title"},{"value":[{"text":"ColorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments"},{"value":[{"text":"ColorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle"},{"value":"IColorData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle"}]}]}