{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Case","title":"ReferenceWhite.D65_2","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D65_2"}],"symbolKind":"case","externalID":"c:@M@NixUniversalSDK@E@ReferenceWhite@ReferenceWhiteD65_2","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"ReferenceWhiteD65_2","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"White point using Illuminant D65 and 2 degree observer.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d65_2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/referencewhite\/d65_2"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_2","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"D65_2","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D65_2":{"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D65_2","title":"ReferenceWhite.D65_2","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"D65_2"}],"type":"topic","abstract":[{"type":"text","text":"White point using Illuminant D65 and 2 degree observer."}],"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhiteD65_2"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d65_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","role":"symbol","abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ReferenceWhiteD65_2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ReferenceWhiteD65_2"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"ReferenceWhiteD65_2","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_2\/title","value":"ReferenceWhiteD65_2"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D65_2\/fragments","value":[{"text":"ReferenceWhiteD65_2","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","value":[{"kind":"identifier","text":"ReferenceWhite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}