{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_PERMISSIONS"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@DeviceScannerState@DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"title":"DeviceScannerState.ERROR_BLUETOOTH_PERMISSIONS","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_permissions"]},{"paths":["\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_permissions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState"]]},"abstract":[{"text":"Bluetooth scanner could not start because Bluetooth permissions have not been granted.","type":"text"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_BLUETOOTH_PERMISSIONS":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_bluetooth_permissions","abstract":[{"type":"text","text":"Bluetooth scanner could not start because Bluetooth permissions have not been granted."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_BLUETOOTH_PERMISSIONS","navigatorTitle":[{"text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"title":"DeviceScannerState.ERROR_BLUETOOTH_PERMISSIONS","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_BLUETOOTH_PERMISSIONS"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","role":"symbol","title":"DeviceScannerState","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceScannerState"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","role":"symbol","title":"IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceScanner","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"IDeviceScanner","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_PERMISSIONS\/title","value":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_BLUETOOTH_PERMISSIONS\/fragments","value":[{"kind":"identifier","text":"DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","value":"DeviceScannerState","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"kind":"identifier","text":"DeviceScannerState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle","value":[{"text":"DeviceScannerState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","value":"IDeviceScanner","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","value":[{"text":"IDeviceScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","value":[{"text":"IDeviceScanner","kind":"identifier"}],"op":"replace"}]}]}