{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Flag to indicate if device RGB feedback is enabled.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rgbFeedbackEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["macOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"rgbFeedbackEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"rgbFeedbackEnabled","kind":"identifier"}],"title":"rgbFeedbackEnabled","required":true,"externalID":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat(py)rgbFeedbackEnabled","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/rgbfeedbackenabled"]},{"paths":["\/documentation\/nixuniversalsdk\/idevicecompat\/rgbfeedbackenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" objects are found nearby using the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"title":"IDeviceCompat","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rgbFeedbackEnabled":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rgbFeedbackEnabled","title":"rgbFeedbackEnabled","navigatorTitle":[{"text":"rgbFeedbackEnabled","kind":"identifier"}],"abstract":[{"text":"Flag to indicate if device RGB feedback is enabled.","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rgbfeedbackenabled","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rgbFeedbackEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","url":"\/documentation\/nixuniversalsdk\/devicescanner","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceScanner","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"title":"DeviceScanner","role":"symbol","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rgbFeedbackEnabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"rgbFeedbackEnabled","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"rgbFeedbackEnabled"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace","value":"IDeviceCompat"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","value":[{"kind":"identifier","text":"IDeviceCompat"}]},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","value":"rgbFeedbackEnabled","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/title"},{"value":[{"kind":"identifier","text":"rgbFeedbackEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rgbFeedbackEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","value":"DeviceScanner","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","value":[{"text":"DeviceScanner","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace","value":[{"text":"DeviceScanner","kind":"identifier"}]}]}]}