{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colordata\/compareto(other:type:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordata\/compareto(other:type:)"]}],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"compareToOther:type:"}],"title":"compareTo(other:type:)","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorData(im)compareToOther:type:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorDifferenceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/compareTo(other:type:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IColorData","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ColorDifferenceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType"},{"kind":"text","text":" = .CIE2000) -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"name":"other","content":[{"inlineContent":[{"text":"Another ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":" instance","type":"text"}],"type":"paragraph"}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"Delta E equation type (defaults to CIE2000)","type":"text"}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Calculate delta E between this color and another. The colors must share the same reference white point ("},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","type":"reference","isActive":true},{"type":"text","text":")."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData"]]},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/reference":{"abstract":[{"text":"Reference white point for this color value.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"reference"}],"title":"reference","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reference"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier","text":"ReferenceWhite"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","url":"\/documentation\/nixuniversalsdk\/colordata\/reference","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","title":"ColorData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorData"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colordata","role":"symbol","abstract":[{"text":"Class describing colorimetry data","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ColorData"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/compareTo(other:type:)":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/compareTo(other:type:)","title":"compareTo(other:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"compareTo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","text":"ColorDifferenceType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"compareToOther:type:","kind":"identifier"}],"abstract":[{"type":"text","text":"Calculate delta E between this color and another. The colors must share the same reference white point ("},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","type":"reference"},{"type":"text","text":")."}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colordata\/compareto(other:type:)","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/icolordata","title":"IColorData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorDifferenceType"}],"type":"topic","title":"ColorDifferenceType","abstract":[{"text":"Enum describing the available color difference (delta E) equations.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"compareToOther:type:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"compareToOther:type:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"compareToOther:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<IColorData>","preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","kind":"typeIdentifier","text":"ColorDifferenceType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Another ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true},{"text":" instance","type":"text"}],"type":"paragraph"}],"name":"other"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Delta E equation type (defaults to CIE2000)","type":"text"}]}],"name":"type"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1reference\/title","op":"replace","value":"reference"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1reference\/fragments","op":"replace","value":[{"kind":"identifier","text":"reference"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/title","op":"replace","value":"ColorData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ColorData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1compareTo(other:type:)\/title","op":"replace","value":"compareToOther:type:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1compareTo(other:type:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"compareToOther:type:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","op":"replace","value":"IColorData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","op":"replace","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title","op":"replace","value":"ColorDifferenceType"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]}]}]}