{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)"},"metadata":{"symbolKind":"method","externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData(im)toRgbValueForReference:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite"},{"kind":"text","text":") -> "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":">?"}],"title":"toRgbValue(reference:)","navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Instance Method","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":">?","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected reference white (defaults to "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","type":"reference","isActive":true},{"text":")","type":"text"}]}],"name":"reference"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"See also: "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"]]},"kind":"symbol","abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(reference:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(reference:)"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(illuminant:observer:)":{"type":"topic","abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the specified white point is not available for this measurement."}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(illuminant:observer:)","title":"toRgbValue(illuminant:observer:)","navigatorTitle":[{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toRgbValue"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":">?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpectralData","kind":"identifier"}],"abstract":[{"type":"text","text":"Class describing spectral data"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","title":"SpectralData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite/D50_2":{"url":"\/documentation\/nixuniversalsdk\/referencewhite\/d50_2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"D50_2"}],"navigatorTitle":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"abstract":[{"type":"text","text":"White point using Illuminant D50 and 2 degree observer."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite\/D50_2","kind":"symbol","role":"symbol","type":"topic","title":"ReferenceWhite.D50_2"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"title":"ReferenceWhite","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReferenceWhite"}],"abstract":[{"type":"text","text":"Enum to describe valid options for reference white IDs"}],"navigatorTitle":[{"text":"ReferenceWhite","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(reference:)":{"type":"topic","abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(reference:)","title":"toRgbValue(reference:)","navigatorTitle":[{"text":"toRgbValueForReference:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":">?","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"toRgbValueForReference:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toRgbValueForReference:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"toRgbValueForReference:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ReferenceWhite","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") ","kind":"text"},{"text":"reference","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"},"op":"replace"},{"value":"toRgbValueForIlluminant:andObserver:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/fragments"},{"value":"SpectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","op":"replace","value":[{"kind":"identifier","text":"SpectralData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","value":[{"kind":"identifier","text":"SpectralData"}],"op":"replace"},{"value":"ReferenceWhiteD50_2","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/title"},{"op":"replace","value":[{"text":"ReferenceWhiteD50_2","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite~1D50_2\/fragments"},{"value":"ReferenceWhite","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","op":"replace","value":[{"text":"ReferenceWhite","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:"},{"value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/fragments"}]}]}