{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"abstract":[{"type":"text","text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula for the textiles application ("},{"code":"kL","type":"codeVoice"},{"type":"text","text":" = 2, "},{"code":"k1","type":"codeVoice"},{"type":"text","text":" = 0.048, "},{"code":"k2","type":"codeVoice"},{"type":"text","text":" = 0.014). Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deltaE94T","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lab1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"lab1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"First CIELAB value (element order L, a, b)"}]}]},{"name":"lab2","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Second CIELAB value (element order L, a, b)"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"dE (CIE1994) value"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/deltae94t(lab1:lab2:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/deltae94t(lab1:lab2:)"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deltaE94T","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lab1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"deltaE94TWithLab1:lab2:","kind":"identifier"}],"role":"symbol","title":"deltaE94T(lab1:lab2:)","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)deltaE94TWithLab1:lab2:","modules":[{"name":"NixUniversalSDK"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94T(lab1:lab2:)"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"url":"\/documentation\/nixuniversalsdk\/colorutils","navigatorTitle":[{"text":"ColorUtils","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorUtils","kind":"identifier"}],"type":"topic","abstract":[{"text":"Color math utility functions","type":"text"}],"title":"ColorUtils"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/deltaE94T(lab1:lab2:)":{"title":"deltaE94T(lab1:lab2:)","url":"\/documentation\/nixuniversalsdk\/colorutils\/deltae94t(lab1:lab2:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/deltaE94T(lab1:lab2:)","navigatorTitle":[{"kind":"identifier","text":"deltaE94TWithLab1:lab2:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deltaE94T","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lab1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"lab2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Takes two CIELAB values and calculates color difference (dE) using CIE1994 formula for the textiles application (","type":"text"},{"type":"codeVoice","code":"kL"},{"text":" = 2, ","type":"text"},{"type":"codeVoice","code":"k1"},{"text":" = 0.048, ","type":"text"},{"type":"codeVoice","code":"k2"},{"text":" = 0.014). Both CIELAB values must share the same reference white. If they do not: convert to XYZ, adapt, convert back to CIELAB before calculating dE.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"deltaE94TWithLab1:lab2:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"deltaE94TWithLab1:lab2:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"deltaE94TWithLab1:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"lab1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"lab2:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"lab2","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"lab1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"First CIELAB value (element order L, a, b)"}]}]},{"name":"lab2","content":[{"inlineContent":[{"type":"text","text":"Second CIELAB value (element order L, a, b)"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"dE (CIE1994) value"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title","op":"replace","value":"ColorUtils"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}]},{"value":"deltaE94TWithLab1:lab2:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94T(lab1:lab2:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1deltaE94T(lab1:lab2:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deltaE94TWithLab1:lab2:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}