{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToCmyk","kind":"identifier"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> [","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"]","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"xyzIn","content":[{"inlineContent":[{"type":"text","text":"XYZ colour, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]},{"name":"xyzRef","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference white value for "},{"type":"codeVoice","code":"xyzIn"},{"type":"text","text":", unity scale (element order X, Y, Z)"}]}]},{"name":"bpc","content":[{"inlineContent":[{"type":"text","text":"Black point compensation enabled \/ disabled"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"CMYK value on unity scale (element order C, M, Y, K)"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"kind":"symbol","abstract":[{"type":"text","text":"Calculates CMYK value from XYZ input using built in lookup tables"}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"xyzToCmyk"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"xyzToCmyk(xyzIn:xyzRef:bpc:)","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:","kind":"identifier"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)xyzToCmykWithXyzIn:xyzRef:bpc:","role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToCmyk(xyzIn:xyzRef:bpc:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"xyzToCmyk"},{"text":"(","kind":"text"},{"text":"xyzIn","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"xyzRef","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"], "},{"text":"bpc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"]","kind":"text"}],"title":"xyzToCmyk(xyzIn:xyzRef:bpc:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToCmyk(xyzIn:xyzRef:bpc:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Calculates CMYK value from XYZ input using built in lookup tables","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztocmyk(xyzin:xyzref:bpc:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"title":"ColorUtils","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"type":"text","text":"Color math utility functions"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"xyzToCmykWithXyzIn:xyzRef:bpc:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"xyzToCmykWithXyzIn:xyzRef:bpc:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"xyzToCmykWithXyzIn:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"xyzIn","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"xyzRef:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"xyzRef","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bpc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"bpc","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"XYZ colour, unity scale (element order X, Y, Z)"}]}],"name":"xyzIn"},{"content":[{"inlineContent":[{"text":"Reference white value for ","type":"text"},{"code":"xyzIn","type":"codeVoice"},{"text":", unity scale (element order X, Y, Z)","type":"text"}],"type":"paragraph"}],"name":"xyzRef"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Black point compensation enabled \/ disabled","type":"text"}]}],"name":"bpc"}],"kind":"parameters"}},{"op":"replace","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"CMYK value on unity scale (element order C, M, Y, K)","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"xyzToCmykWithXyzIn:xyzRef:bpc:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"xyzToCmykWithXyzIn:xyzRef:bpc:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToCmyk(xyzIn:xyzRef:bpc:)\/fragments"},{"value":"ColorUtils","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","op":"replace","value":[{"text":"ColorUtils","kind":"identifier"}]}]}]}