{"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Calculates linear RGB from XYZ given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztorgb(xyzin:refin:rchrom:gchrom:bchrom:wchrom:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colorutils\/xyztorgb(xyzin:refin:rchrom:gchrom:bchrom:wchrom:)"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"]]},"metadata":{"roleHeading":"Type Method","modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:"}],"externalID":"c:@M@NixUniversalSDK@objc(cs)ColorUtils(cm)xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:","symbolKind":"method","role":"symbol","title":"xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"xyzToRgb","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"xyzIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refIn"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"rChrom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"gChrom"},{"kind":"text","text":": "},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"bChrom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"wChrom"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"xyzToRgb"},{"kind":"text","text":"("},{"text":"xyzIn","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","kind":"typeIdentifier","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refIn"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"kind":"text","text":"<"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"rChrom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"gChrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"bChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":">, "},{"text":"wChrom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"xyzIn","content":[{"inlineContent":[{"type":"text","text":"Input colour XYZ values, unity scale (element order X, Y, Z)"}],"type":"paragraph"}]},{"name":"refIn","content":[{"inlineContent":[{"text":"Reference white of input colour ","type":"text"},{"code":"xyzIn","type":"codeVoice"},{"type":"text","text":", unity scale (element order X, Y, Z)"}],"type":"paragraph"}]},{"name":"rChrom","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space red primary chromaticity coordinates (element order x, y)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"RGB space green primary chromaticity coordinates (element order x, y)","type":"text"}]}],"name":"gChrom"},{"name":"bChrom","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space blue primary chromaticity coordinates (element order x, y)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"RGB space reference white\/grey chromaticity coordinates (element order x, y)"}],"type":"paragraph"}],"name":"wChrom"}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Linear RGB value, unity scale, (element order R, G, B)"}]}],"kind":"content"}],"sections":[],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils\/xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","title":"xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)","navigatorTitle":[{"text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colorutils\/xyztorgb(xyzin:refin:rchrom:gchrom:bchrom:wchrom:)","abstract":[{"type":"text","text":"Calculates linear RGB from XYZ given chromaticity coordinates of RGB working space primaries and reference whites of RGB and XYZ value"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"xyzToRgb","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"xyzIn"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"refIn"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"rChrom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"gChrom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"bChrom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sa","text":"Array"},{"text":"<","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"wChrom"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":">"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","type":"topic","title":"ColorUtils","kind":"symbol","abstract":[{"type":"text","text":"Color math utility functions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorUtils","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"xyzToRgbWithXyzIn:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"xyzIn"},{"kind":"text","text":" "},{"text":"refIn:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"refIn"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rChrom:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rChrom"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gChrom:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"gChrom"},{"kind":"text","text":" "},{"kind":"identifier","text":"bChrom:"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bChrom","kind":"internalParam"},{"kind":"text","text":" "},{"text":"wChrom:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"wChrom","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"xyzIn","content":[{"type":"paragraph","inlineContent":[{"text":"Input colour XYZ values, unity scale (element order X, Y, Z)","type":"text"}]}]},{"name":"refIn","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference white of input colour "},{"code":"xyzIn","type":"codeVoice"},{"text":", unity scale (element order X, Y, Z)","type":"text"}]}]},{"name":"rChrom","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space red primary chromaticity coordinates (element order x, y)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"RGB space green primary chromaticity coordinates (element order x, y)"}]}],"name":"gChrom"},{"name":"bChrom","content":[{"inlineContent":[{"text":"RGB space blue primary chromaticity coordinates (element order x, y)","type":"text"}],"type":"paragraph"}]},{"name":"wChrom","content":[{"inlineContent":[{"text":"RGB space reference white\/grey chromaticity coordinates (element order x, y)","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Linear RGB value, unity scale, (element order R, G, B)"}]}],"kind":"content"}},{"op":"replace","value":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils~1xyzToRgb(xyzIn:refIn:rChrom:gChrom:bChrom:wChrom:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"xyzToRgbWithXyzIn:refIn:rChrom:gChrom:bChrom:wChrom:"}]},{"op":"replace","value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"ColorUtils"}],"op":"replace"}]}]}