{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"ColorDifferenceTypeCMC2_1","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CMC2_1","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:@M@NixUniversalSDK@E@ColorDifferenceType@ColorDifferenceTypeCMC2_1","title":"ColorDifferenceType.CMC2_1","roleHeading":"Case","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC2_1","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cmc2_1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/colordifferencetype\/cmc2_1"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CMC2_1"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Color difference using CMC(l:c) equation with l = 2, and c = 1 (‘threshold of acceptability’)"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorDifferenceType"}],"navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"kind":"symbol","title":"ColorDifferenceType","type":"topic","role":"symbol","abstract":[{"text":"Enum describing the available color difference (delta E) equations.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType/CMC2_1":{"url":"\/documentation\/nixuniversalsdk\/colordifferencetype\/cmc2_1","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType\/CMC2_1","role":"symbol","title":"ColorDifferenceType.CMC2_1","abstract":[{"type":"text","text":"Color difference using CMC(l:c) equation with l = 2, and c = 1 (‘threshold of acceptability’)"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMC2_1"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorDifferenceTypeCMC2_1"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ColorDifferenceTypeCMC2_1"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceTypeCMC2_1"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"kind":"identifier","text":"ColorDifferenceTypeCMC2_1"}]}]}},{"value":"ColorDifferenceType","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC2_1\/title","value":"ColorDifferenceTypeCMC2_1","op":"replace"},{"op":"replace","value":[{"text":"ColorDifferenceTypeCMC2_1","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType~1CMC2_1\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}