{"sections":[],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","interfaceLanguage":"swift"},"primaryContentSections":[{"mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes"],"kind":"mentions"},{"kind":"content","content":[{"text":"Overview","anchor":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This framework was written to allow integration of Nix devices into third-party iOS and macOS applications. It provides tools to discover nearby Nix devices, open a connection, perform measurements, and obtain data. Tools are also provided for basic colour conversions and colour difference calculations."}],"type":"paragraph"},{"inlineContent":[{"text":"The latest version of this documentation is available ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/www.nixsensor.com\/sdk-doc-ios"},{"text":" and the latest verion of the library is available on ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist"},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For changes introduced in this version, please refer to the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"name":"Note","content":[{"inlineContent":[{"text":"If you are upgrading to version 4.2.x or newer from an earlier version, you will need update your application to activate your SDK license. See ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","isActive":true,"type":"reference"},{"text":" for more details.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"},{"name":"Warning","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","isActive":true,"type":"reference"},{"type":"text","text":" replaces the previous "},{"code":"NixFramework","type":"codeVoice"},{"type":"text","text":" framework. These two libraries should not be used together; remove the "},{"code":"NixFramework","type":"codeVoice"},{"type":"text","text":" library from your project before adding "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","style":"warning"},{"type":"heading","anchor":"Minimum-requirements","text":"Minimum requirements","level":3},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Xcode (tested with Xcode 26.4)","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Supported operating systems:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"iOS: 12.0 and newer","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"macOS: 10.13 and newer"}]}]}]}]},{"content":[{"inlineContent":[{"text":"BLE connectivity supported on iOS and macOS","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"USB connectivity supported on macOS only","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Active internet connection for device activation (demo \/ evaluation versions only)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Supported Nix devices:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix Mini"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Nix Mini 2"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Nix Mini 3"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix Pro"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix Pro 2"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Nix QC"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix Spectro 2"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Nix Spectro L"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]},{"type":"heading","text":"Quick Start Guide","level":3,"anchor":"Quick-Start-Guide"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Review the step-by-step guide provided in the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Getting-Started","isActive":true},{"text":" section below.","type":"text"}]},{"anchor":"Other-Platforms","text":"Other Platforms","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Aside from macOS and iOS, alternate versions of the "},{"type":"codeVoice","code":"NixUniversalSDK"},{"type":"text","text":" are available for other platforms. If you are looking to add Nix device support to Android or Windows applications please visit the following pages for further information."}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NixUniversalSDK for "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.nixsensor.com\/sdk-doc-android"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"NixUniversalSDK for "},{"identifier":"https:\/\/www.nixsensor.com\/sdk-doc-windows","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"type":"unorderedList"},{"anchor":"Additional-Support","text":"Additional Support","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"This quick start guide is not intended as an exhaustive reference. Please also refer to the API references included below for further details on the classes and methods provided by the Nix Universal SDK.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you encounter any issues with SDK implementation, please contact us via e-mail at "},{"identifier":"mailto:sdk@nixsensor.com","type":"reference","isActive":true},{"type":"text","text":"."}]},{"anchor":"Privacy-Disclaimer","text":"Privacy Disclaimer","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"Limited anonymous usage data is tracked by the Nix Universal SDK using Google Analytics. No personal user data, color data, or any data which uniquely identifies an individual Nix device is collected. Collected data is subject to the Nix Apps ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/www.nixsensor.com\/nix-apps-privacy-policy\/"},{"text":". Events and usage data tracked by the Nix SDK are solely limited to the following information:","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"Device connection events:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Device type (e.g. - Nix Pro, Nix Mini, etc)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device manufacturing batch identifier","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix SDK version"}]}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device color scan events:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Device type"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Nix SDK version"}]}]}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Reference tile usage events:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Device type"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Device diagnostics information","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Nix SDK version","type":"text"}],"type":"paragraph"}]}]}]}],"type":"unorderedList"}]}],"topicSections":[{"title":"Getting Started","anchor":"Getting-Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"]},{"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"],"generated":true},{"title":"Protocols","anchor":"Protocols","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate"],"generated":true},{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/==(_:_:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/_(_:_:)-1qzrk","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/_(_:_:)-ubpg"],"generated":true},{"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"],"generated":true},{"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"],"generated":true},{"title":"Extended Modules","anchor":"Extended-Modules","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift"],"generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[[]]},"kind":"symbol","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"module","roleHeading":"Framework","modules":[{"name":"NixUniversalSDK"}],"role":"collection","title":"NixUniversalSDK","externalID":"NixUniversalSDK"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/faq":{"url":"\/documentation\/nixuniversalsdk\/faq","role":"article","type":"topic","abstract":[{"text":"Troubleshooting common issues","type":"text"}],"title":"Frequently Asked Questions","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"text":"IColorData","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IColorData","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","title":"IColorData","abstract":[{"text":"Protocol describing colorimetry data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/icolordata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScannerStateDelegate"}],"title":"ScannerStateDelegate","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate","navigatorTitle":[{"kind":"identifier","text":"ScannerStateDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol definition for a callback to be invoked when an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true},{"type":"text","text":" starts or stops a search."}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceCompatNonnull":{"title":"DeviceCompatNonnull","url":"\/documentation\/nixuniversalsdk\/devicecompatnonnull","type":"topic","abstract":[{"text":"Non-null instance of an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatNonnull","kind":"symbol","fragments":[{"kind":"identifier","text":"DeviceCompatNonnull"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralDataNonnull":{"fragments":[{"text":"SpectralDataNonnull","kind":"identifier"}],"title":"SpectralDataNonnull","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNonnull","role":"symbol","abstract":[{"text":"Non-null instance of an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","type":"reference"},{"text":" object","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/spectraldatanonnull"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityDataNonnull":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNonnull","role":"symbol","fragments":[{"text":"DensityDataNonnull","kind":"identifier"}],"title":"DensityDataNonnull","url":"\/documentation\/nixuniversalsdk\/densitydatanonnull","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Non-null instance of an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},{"type":"text","text":" object"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"url":"\/documentation\/nixuniversalsdk\/device-operations","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","role":"article","title":"Device Operations","abstract":[{"type":"text","text":"Take measurements, set device options, and query device properties"}],"kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","role":"article","title":"Activating the SDK License","url":"\/documentation\/nixuniversalsdk\/activating-license","type":"topic","kind":"article","abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"InterfaceType","kind":"identifier"}],"navigatorTitle":[{"text":"InterfaceType","kind":"identifier"}],"title":"InterfaceType","url":"\/documentation\/nixuniversalsdk\/interfacetype","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorUtils":{"title":"ColorUtils","navigatorTitle":[{"kind":"identifier","text":"ColorUtils"}],"url":"\/documentation\/nixuniversalsdk\/colorutils","abstract":[{"type":"text","text":"Color math utility functions"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorUtils"}],"role":"symbol"},"https://www.nixsensor.com/sdk-doc-ios":{"titleInlineContent":[{"type":"text","text":"online"}],"url":"https:\/\/www.nixsensor.com\/sdk-doc-ios","identifier":"https:\/\/www.nixsensor.com\/sdk-doc-ios","title":"online","type":"link"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralDataNullable":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNullable","role":"symbol","fragments":[{"kind":"identifier","text":"SpectralDataNullable"}],"title":"SpectralDataNullable","url":"\/documentation\/nixuniversalsdk\/spectraldatanullable","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Nullable instance of an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"},{"type":"text","text":" object"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDensityData":{"url":"\/documentation\/nixuniversalsdk\/idensitydata","navigatorTitle":[{"kind":"identifier","text":"IDensityData"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol describing density data"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IDensityData","kind":"identifier"}],"title":"IDensityData","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData"},"mailto:sdk@nixsensor.com":{"type":"link","identifier":"mailto:sdk@nixsensor.com","url":"mailto:sdk@nixsensor.com","title":"sdk@nixsensor.com","titleInlineContent":[{"text":"sdk@nixsensor.com","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","navigatorTitle":[{"kind":"identifier","text":"DeviceStateDelegate"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Definition for a callback from an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStateDelegate"}],"title":"DeviceStateDelegate","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDataNullable":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNullable","role":"symbol","fragments":[{"text":"ColorDataNullable","kind":"identifier"}],"title":"ColorDataNullable","url":"\/documentation\/nixuniversalsdk\/colordatanullable","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Nullable instance of an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"text":" object","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementDictionary":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDictionary","role":"symbol","fragments":[{"text":"MeasurementDictionary","kind":"identifier"}],"title":"MeasurementDictionary","url":"\/documentation\/nixuniversalsdk\/measurementdictionary","kind":"symbol","type":"topic","abstract":[{"text":"Dictionary providing ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"type":"text","text":" mapped to measurement modes"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceCompatBlock":{"title":"DeviceCompatBlock","url":"\/documentation\/nixuniversalsdk\/devicecompatblock","type":"topic","abstract":[{"type":"text","text":"Completion block providing a nullable "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatBlock","kind":"symbol","fragments":[{"text":"DeviceCompatBlock","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData":{"navigatorTitle":[{"text":"ColorData","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ColorData","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","title":"ColorData","abstract":[{"text":"Class describing colorimetry data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colordata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityStatus","kind":"identifier"}],"navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}],"title":"DensityStatus","url":"\/documentation\/nixuniversalsdk\/densitystatus","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Enum to describe the available options for density status"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"navigatorTitle":[{"text":"ColorType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ColorType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","title":"ColorType","abstract":[{"text":"Enum to describe the base color data types available for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"url":"\/documentation\/nixuniversalsdk\/colortype","role":"symbol"},"https://www.github.com/nixsensor/nix-universal-sdk-ios-dist":{"title":"GitHub","titleInlineContent":[{"type":"text","text":"GitHub"}],"url":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist","identifier":"https:\/\/www.github.com\/nixsensor\/nix-universal-sdk-ios-dist","type":"link"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/_(_:_:)-ubpg":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/_(_:_:)-ubpg","type":"topic","title":"<(_:_:)","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"<"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IDeviceCompat","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","kind":"typeIdentifier","text":"IDeviceCompat"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/_(_:_:)-ubpg"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceFoundCallback":{"url":"\/documentation\/nixuniversalsdk\/devicefoundcallback","abstract":[{"type":"text","text":"Definition for a closure invoked when an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true},{"type":"text","text":" has discovered a supported Nix device"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback","navigatorTitle":[{"kind":"identifier","text":"DeviceFoundCallback"}],"title":"DeviceFoundCallback","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceFoundCallback"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Swift":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Swift","type":"topic","title":"Swift","abstract":[],"kind":"symbol","role":"collection","url":"\/documentation\/nixuniversalsdk\/swift"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"url":"\/documentation\/nixuniversalsdk\/devicestatus","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","role":"symbol","title":"DeviceStatus","abstract":[{"text":"Enum describing the possible causes of a device disconnection event in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DeviceStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityDataNullable":{"url":"\/documentation\/nixuniversalsdk\/densitydatanullable","abstract":[{"text":"Nullable instance of an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","type":"reference","isActive":true},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNullable","title":"DensityDataNullable","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"DensityDataNullable"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState":{"url":"\/documentation\/nixuniversalsdk\/devicescannerstate","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","role":"symbol","title":"DeviceScannerState","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceScannerState"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceScannerState"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceVersion":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceVersion","kind":"identifier"}],"title":"DeviceVersion","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion","navigatorTitle":[{"text":"DeviceVersion","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Class to describe Nix device revisions","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/deviceversion"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/_(_:_:)-1qzrk":{"url":"\/documentation\/nixuniversalsdk\/_(_:_:)-1qzrk","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/_(_:_:)-1qzrk","title":">(_:_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":">"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","kind":"typeIdentifier","text":"IDeviceCompat"},{"text":", ","kind":"text"},{"text":"IDeviceCompat","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"https://www.nixsensor.com/sdk-doc-windows":{"title":"Windows (.NET)","type":"link","titleInlineContent":[{"text":"Windows (.NET)","type":"text"}],"identifier":"https:\/\/www.nixsensor.com\/sdk-doc-windows","url":"https:\/\/www.nixsensor.com\/sdk-doc-windows"},"https://www.nixsensor.com/sdk-doc-android":{"titleInlineContent":[{"text":"Android","type":"text"}],"type":"link","url":"https:\/\/www.nixsensor.com\/sdk-doc-android","identifier":"https:\/\/www.nixsensor.com\/sdk-doc-android","title":"Android"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/==(_:_:)":{"url":"\/documentation\/nixuniversalsdk\/==(_:_:)","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/==(_:_:)","title":"==(_:_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"=="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerNonnull":{"fragments":[{"kind":"identifier","text":"DeviceScannerNonnull"}],"title":"DeviceScannerNonnull","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNonnull","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-null instance of an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","type":"reference","isActive":true},{"type":"text","text":" object"}],"url":"\/documentation\/nixuniversalsdk\/devicescannernonnull"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","role":"article","title":"Adding to Your Xcode Project","url":"\/documentation\/nixuniversalsdk\/add-to-xcode","kind":"article","type":"topic","abstract":[{"text":"Add the library bundle to your project and declare peripheral uses","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Illuminant":{"url":"\/documentation\/nixuniversalsdk\/illuminant","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","role":"symbol","title":"Illuminant","abstract":[{"text":"Enum to describe the available options for reference illuminant","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Illuminant","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Illuminant","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","title":"ISpectralData","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"https://www.nixsensor.com/nix-apps-privacy-policy/":{"type":"link","title":"privacy policy","identifier":"https:\/\/www.nixsensor.com\/nix-apps-privacy-policy\/","titleInlineContent":[{"type":"text","text":"privacy policy"}],"url":"https:\/\/www.nixsensor.com\/nix-apps-privacy-policy\/"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IMeasurementData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","type":"topic","title":"IMeasurementData","abstract":[{"type":"text","text":"Protocol defining the properties and methods provided by Nix device measurements. These objects are provided in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":" callback after a measurement is taken using an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"text":" instance, or can be reconstructed from raw string data using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IMeasurementData","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"IMeasurementData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/imeasurementdata"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/CommandStatus":{"url":"\/documentation\/nixuniversalsdk\/commandstatus","navigatorTitle":[{"text":"CommandStatus","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Enum describing the possible status of commands executed by the Nix device, as provided in the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommandStatus","kind":"identifier"}],"title":"CommandStatus","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"type":"topic","title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/universalsdkVersionString":{"title":"universalsdkVersionString","url":"\/documentation\/nixuniversalsdk\/universalsdkversionstring","type":"topic","abstract":[{"type":"text","text":"Project version string for universalsdk."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/universalsdkVersionString","kind":"symbol","fragments":[{"text":"universalsdkVersionString","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData","type":"topic","title":"MeasurementData","kind":"symbol","abstract":[{"text":"Class describing measurement data from a Nix device","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MeasurementData"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MeasurementData"}],"url":"\/documentation\/nixuniversalsdk\/measurementdata"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","type":"topic","title":"LicenseFeature","abstract":[{"text":"Enum describing the optional features that can be enabled by the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". Feature availability can be queried using ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFeature","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementData/fromRaw(_:)":{"title":"fromRaw(_:)","url":"\/documentation\/nixuniversalsdk\/measurementdata\/fromraw(_:)","abstract":[{"type":"text","text":"Reconstructs a "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","isActive":true},{"type":"text","text":" instance from its raw string value, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the data is invalid."}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData\/fromRaw(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromRaw"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"IMeasurementData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IMeasurementData"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"title":"DeviceScanner","navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","type":"topic","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DeviceScanner","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityData":{"url":"\/documentation\/nixuniversalsdk\/densitydata","navigatorTitle":[{"text":"DensityData","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Class describing density data","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DensityData","kind":"identifier"}],"title":"DensityData","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceState":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceState","kind":"identifier"}],"title":"DeviceState","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","navigatorTitle":[{"kind":"identifier","text":"DeviceState"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"}],"url":"\/documentation\/nixuniversalsdk\/devicestate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDifferenceType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorDifferenceType"}],"navigatorTitle":[{"text":"ColorDifferenceType","kind":"identifier"}],"kind":"symbol","title":"ColorDifferenceType","type":"topic","role":"symbol","abstract":[{"text":"Enum describing the available color difference (delta E) equations.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/colordifferencetype","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerNullable":{"title":"DeviceScannerNullable","url":"\/documentation\/nixuniversalsdk\/devicescannernullable","type":"topic","abstract":[{"type":"text","text":"Nullable instance of an "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNullable","kind":"symbol","fragments":[{"kind":"identifier","text":"DeviceScannerNullable"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"title":"Discovering and Connecting to Nix Devices","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","abstract":[{"text":"Use the device scanner to discover Nix devices and open a connection","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","kind":"article","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"url":"\/documentation\/nixuniversalsdk\/release-notes","abstract":[{"text":"Review the changes made in this version of the library","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","title":"Release Notes","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScanMode":{"url":"\/documentation\/nixuniversalsdk\/scanmode","abstract":[{"text":"Enum to describe the measurement modes used by Nix devices","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode","navigatorTitle":[{"text":"ScanMode","kind":"identifier"}],"title":"ScanMode","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanMode"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceCompatNullable":{"title":"DeviceCompatNullable","url":"\/documentation\/nixuniversalsdk\/devicecompatnullable","type":"topic","abstract":[{"text":"Nullable instance of an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatNullable","kind":"symbol","fragments":[{"kind":"identifier","text":"DeviceCompatNullable"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceResultCallback":{"url":"\/documentation\/nixuniversalsdk\/deviceresultcallback","navigatorTitle":[{"kind":"identifier","text":"DeviceResultCallback"}],"role":"symbol","abstract":[{"type":"text","text":"Definition for a closure providing a command result, invoked after executing an asynchronous command on an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"type":"text","text":" instance."}],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceResultCallback","kind":"identifier"}],"title":"DeviceResultCallback","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceResultCallback"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceCompat","kind":"identifier"}],"navigatorTitle":[{"text":"IDeviceCompat","kind":"identifier"}],"title":"IDeviceCompat","url":"\/documentation\/nixuniversalsdk\/idevicecompat","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Protocol describing the supported properties and methods for a Nix device. "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" objects are found nearby using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isFeatureEnabled(_:)":{"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isfeatureenabled(_:)","abstract":[{"type":"text","text":"Helper to check if a particular "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"},{"type":"text","text":" is enabled by the current license."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"isFeatureEnabled:","kind":"identifier"}],"title":"isFeatureEnabled(_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isFeatureEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LicenseFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseFeature"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","role":"article","abstract":[{"text":"Explore source code for demo iOS and macOS applications","type":"text"}],"type":"topic","title":"Example Applications","kind":"article","url":"\/documentation\/nixuniversalsdk\/example-apps"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralData"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","title":"SpectralData","abstract":[{"text":"Class describing spectral data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/Observer":{"title":"Observer","navigatorTitle":[{"text":"Observer","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/observer","type":"topic","abstract":[{"text":"Enum to describe the available options for reference observer","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Observer","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementDataNonnull":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDataNonnull","type":"topic","title":"MeasurementDataNonnull","abstract":[{"text":"Non-null instance of an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"text":" object","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"MeasurementDataNonnull"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/measurementdatanonnull"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorDataNonnull":{"fragments":[{"kind":"identifier","text":"ColorDataNonnull"}],"title":"ColorDataNonnull","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNonnull","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Non-null instance of an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","isActive":true,"type":"reference"},{"type":"text","text":" object"}],"url":"\/documentation\/nixuniversalsdk\/colordatanonnull"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ReferenceWhite":{"navigatorTitle":[{"kind":"identifier","text":"ReferenceWhite"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReferenceWhite"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","title":"ReferenceWhite","abstract":[{"text":"Enum to describe valid options for reference white IDs","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/referencewhite","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","role":"symbol","title":"IDeviceScanner","abstract":[{"type":"text","text":"Protocol implemented by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDeviceScanner","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"IDeviceScanner","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/MeasurementDataNullable":{"title":"MeasurementDataNullable","url":"\/documentation\/nixuniversalsdk\/measurementdatanullable","abstract":[{"text":"Nullable instance of an ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData"},{"type":"text","text":" object"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDataNullable","kind":"symbol","fragments":[{"text":"MeasurementDataNullable","kind":"identifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerState"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","type":"topic","title":"LicenseManagerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManagerState"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"reference","isActive":true},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","title":"DeviceType","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"url":"\/documentation\/nixuniversalsdk\/devicetype","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManager"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"title":"LicenseManager","url":"\/documentation\/nixuniversalsdk\/licensemanager","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"url":"\/documentation\/nixuniversalsdk\/wrapper","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","role":"article","title":"Wrapper for Usage in C\/C++","abstract":[{"text":"Review an example project which provides a C\/C++ interface for macOS applications","type":"text"}],"kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK#Getting-Started":{"title":"Getting Started","url":"\/documentation\/nixuniversalsdk#Getting-Started","type":"topic","abstract":[],"kind":"section","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Getting-Started"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/universalsdkVersionNumber":{"fragments":[{"text":"universalsdkVersionNumber","kind":"identifier"}],"title":"universalsdkVersionNumber","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/universalsdkVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for universalsdk."}],"type":"topic","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/universalsdkversionnumber"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/faq","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"title":"Getting Started","anchor":"Getting-Started"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorUtils","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceVersion","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDensityData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IMeasurementData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate"],"title":"Protocols","generated":true,"anchor":"Protocols"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/universalsdkVersionNumber","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/universalsdkVersionString"],"title":"Variables","generated":true,"anchor":"Variables"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDataNullable","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityDataNullable","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatBlock","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceCompatNullable","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerNullable","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDataNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDataNullable","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/MeasurementDictionary","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNonnull","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNullable"],"title":"Type Aliases","generated":true,"anchor":"Type-Aliases"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorDifferenceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/CommandStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Illuminant","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/Observer","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ReferenceWhite","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScanMode"],"title":"Enumerations","generated":true,"anchor":"Enumerations"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments","op":"replace","value":[{"kind":"identifier","text":"IColorData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","value":[{"text":"IColorData","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/title","op":"replace","value":"ScannerStateDelegate"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/fragments","op":"replace","value":[{"text":"ScannerStateDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/navigatorTitle","op":"replace","value":[{"text":"ScannerStateDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title","value":"InterfaceType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"InterfaceType"}]},{"op":"replace","value":[{"text":"InterfaceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle"},{"op":"replace","value":"ColorUtils","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/fragments","value":[{"text":"ColorUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorUtils\/navigatorTitle","value":[{"kind":"identifier","text":"ColorUtils"}],"op":"replace"},{"op":"replace","value":"IDensityData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/title"},{"op":"replace","value":[{"text":"IDensityData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/fragments"},{"value":[{"text":"IDensityData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDensityData\/navigatorTitle"},{"value":"DeviceStateDelegate","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title"},{"value":[{"kind":"identifier","text":"DeviceStateDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments"},{"value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/title","op":"replace","value":"ColorData"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/fragments","op":"replace","value":[{"text":"ColorData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/navigatorTitle","value":[{"text":"ColorData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","value":"DensityStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments","value":[{"text":"DensityStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DensityStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","value":"ColorType"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"text":"ColorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle","value":[{"text":"ColorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title","value":"DeviceStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments","value":[{"text":"DeviceStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/navigatorTitle","value":[{"text":"DeviceStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/title","value":"DeviceScannerState"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/fragments","value":[{"kind":"identifier","text":"DeviceScannerState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState\/navigatorTitle","value":[{"text":"DeviceScannerState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/title","value":"DeviceVersion"},{"value":[{"kind":"identifier","text":"DeviceVersion"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/fragments"},{"value":[{"text":"DeviceVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceVersion\/navigatorTitle"},{"value":"Illuminant","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/title"},{"value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/fragments"},{"value":[{"text":"Illuminant","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Illuminant\/navigatorTitle"},{"value":"ISpectralData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title"},{"value":[{"kind":"identifier","text":"ISpectralData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"value":"IMeasurementData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/title"},{"value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IMeasurementData\/navigatorTitle","value":[{"text":"IMeasurementData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/title","value":"CommandStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/fragments","value":[{"text":"CommandStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1CommandStatus\/navigatorTitle","value":[{"kind":"identifier","text":"CommandStatus"}],"op":"replace"},{"op":"replace","value":"MeasurementData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MeasurementData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/fragments"},{"op":"replace","value":[{"text":"MeasurementData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1MeasurementData\/navigatorTitle"},{"op":"replace","value":"LicenseFeature","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle"},{"op":"replace","value":"DeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle"},{"op":"replace","value":"DensityData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DensityData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DensityData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityData\/navigatorTitle"},{"op":"replace","value":"DeviceState","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceState"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceState\/navigatorTitle"},{"op":"replace","value":"ColorDifferenceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ColorDifferenceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/fragments"},{"value":[{"kind":"identifier","text":"ColorDifferenceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorDifferenceType\/navigatorTitle","op":"replace"},{"value":"ScanMode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/title","op":"replace"},{"value":[{"text":"ScanMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/fragments","op":"replace"},{"value":[{"text":"ScanMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScanMode\/navigatorTitle","op":"replace"},{"value":"IDeviceCompat","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace"},{"op":"replace","value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle"},{"op":"replace","value":"isFeatureEnabled:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isFeatureEnabled:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isFeatureEnabled(_:)\/fragments"},{"op":"replace","value":"SpectralData","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title"},{"op":"replace","value":[{"text":"SpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SpectralData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/title","op":"replace","value":"Observer"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/fragments","op":"replace","value":[{"kind":"identifier","text":"Observer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1Observer\/navigatorTitle","value":[{"kind":"identifier","text":"Observer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/title","value":"ReferenceWhite"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/fragments","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ReferenceWhite\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ReferenceWhite"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","op":"replace","value":"IDeviceScanner"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","op":"replace","value":[{"text":"IDeviceScanner","kind":"identifier"}]},{"value":"LicenseManagerState","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments","op":"replace","value":[{"text":"LicenseManagerState","kind":"identifier"}]},{"value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","value":"DeviceType"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments"},{"op":"replace","value":[{"text":"DeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}