{"abstract":[{"text":"Class describing colorimetry data","type":"text"}],"metadata":{"roleHeading":"Class","title":"ColorData","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorData"}],"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorData"}],"symbolKind":"class","externalID":"c:@M@NixUniversalSDK@objc(cs)ColorData"},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"sections":[],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/init(xyz:reference:mode:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/rgbValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/type","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value"]},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/compareTo(other:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/convertTo(type:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/colordata"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/colordata"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorData"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/reference":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"reference","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"reference"}],"abstract":[{"text":"Reference white point for this color value.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","title":"reference","url":"\/documentation\/nixuniversalsdk\/colordata\/reference","role":"symbol"},"doc://com.nixsensor.universalsdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorType":{"title":"ColorType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ColorType"}],"url":"\/documentation\/nixuniversalsdk\/colortype","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","kind":"symbol","abstract":[{"type":"text","text":"Enum to describe the base color data types available for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"},{"type":"text","text":" objects. Values for each of these types can be freely converted to each other without loss of color data."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ColorType"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/init(xyz:reference:mode:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"xyz","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":">, ","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier","text":"ScanMode"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/colordata\/init(xyz:reference:mode:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/init(xyz:reference:mode:)","role":"symbol","title":"init(xyz:reference:mode:)","abstract":[]},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP"},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"value","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value","type":"topic","role":"symbol","url":"\/documentation\/nixuniversalsdk\/colordata\/value","abstract":[{"text":"Color value (3 coordinates) in the format specified by ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IColorData":{"navigatorTitle":[{"kind":"identifier","text":"IColorData"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData","url":"\/documentation\/nixuniversalsdk\/icolordata","abstract":[{"type":"text","text":"Protocol describing colorimetry data"}],"kind":"symbol","title":"IColorData","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IColorData"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/compareTo(other:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/compareTo(other:type:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"compareTo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"other"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorDifferenceType","text":"ColorDifferenceType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"compareToOther:type:"}],"url":"\/documentation\/nixuniversalsdk\/colordata\/compareto(other:type:)","type":"topic","abstract":[{"type":"text","text":"Calculate delta E between this color and another. The colors must share the same reference white point ("},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference"},{"text":").","type":"text"}],"title":"compareTo(other:type:)","role":"symbol"},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/type":{"url":"\/documentation\/nixuniversalsdk\/colordata\/type","role":"symbol","abstract":[{"type":"text","text":"Type of color data stored in the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value"},{"text":" field.","type":"text"}],"title":"type","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier","text":"ColorType"}],"kind":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/rgbValue":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/rgbValue","role":"symbol","title":"rgbValue","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rgbValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":">"}],"url":"\/documentation\/nixuniversalsdk\/colordata\/rgbvalue","navigatorTitle":[{"kind":"identifier","text":"rgbValue"}],"abstract":[{"text":"sRGB value for this color.","type":"text"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/mode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode","type":"topic","abstract":[{"text":"Scan mode for this value.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"text":": ","kind":"text"},{"text":"ScanMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode"}],"title":"mode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"mode","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colordata\/mode"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData/convertTo(type:)":{"abstract":[{"type":"text","text":"Convert this color value to another "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorType","isActive":true},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/convertTo(type:)","navigatorTitle":[{"kind":"identifier","text":"convertToType:"}],"title":"convertTo(type:)","url":"\/documentation\/nixuniversalsdk\/colordata\/convertto(type:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"convertTo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ColorType","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ColorData":{"abstract":[{"text":"Class describing colorimetry data","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ColorData","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/colordata","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ColorData","kind":"identifier"}],"title":"ColorData"},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.nixsensor.universalsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"ColorData","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ColorData","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ColorData","kind":"identifier"}]},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/reference","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/rgbValue","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/type","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/value"],"generated":true,"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/compareTo(other:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ColorData\/convertTo(type:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IColorData"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ColorData","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1reference\/title","value":"reference","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1reference\/fragments","value":[{"text":"reference","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/title","value":"ColorType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/fragments","value":[{"kind":"identifier","text":"ColorType"}]},{"value":[{"kind":"identifier","text":"ColorType"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1value\/title","op":"replace","value":"value"},{"op":"replace","value":[{"kind":"identifier","text":"value"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1value\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/title","value":"IColorData","op":"replace"},{"value":[{"text":"IColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IColorData\/navigatorTitle","value":[{"text":"IColorData","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1compareTo(other:type:)\/title","value":"compareToOther:type:"},{"value":[{"text":"- ","kind":"text"},{"text":"compareToOther:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1compareTo(other:type:)\/fragments"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1rgbValue\/title","value":"rgbValue"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1rgbValue\/fragments","op":"replace","value":[{"text":"rgbValue","kind":"identifier"}]},{"op":"replace","value":"mode","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1mode\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1mode\/fragments","op":"replace","value":[{"text":"mode","kind":"identifier"}]},{"value":"convertToType:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1convertTo(type:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"convertToType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData~1convertTo(type:)\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/title","value":"ColorData","op":"replace"},{"value":[{"text":"ColorData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ColorData\/navigatorTitle","value":[{"kind":"identifier","text":"ColorData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}