{"kind":"article","abstract":[{"type":"text","text":"Use the device scanner to discover Nix devices and open a connection"}],"sections":[],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"title":"Getting Started","anchor":"Getting-Started"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/discovering-connecting"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/discovering-connecting"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"metadata":{"title":"Discovering and Connecting to Nix Devices","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Article","role":"article"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Regardless of device type, each unique Nix device can be represented by an object that conforms to the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":" protocol. To obtain instances of the device object, they need to first be discovered using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"text":". They can also be recalled at a later time directly using their ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id"},{"text":" property (for Bluetooth connected devices only).","type":"text"}]},{"type":"heading","anchor":"Device-Discovery","text":"Device Discovery","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":" implements the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"},{"type":"text","text":" protocol and searches for nearby Nix devices using Bluetooth. On macOS, the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner"},{"type":"text","text":" will also report devices connected via USB. Scanner events are reported via:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Delegate which must be specified when initializing the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reports when the scanner initializes, starts, and stops searching for devices"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Closure which is called by the scanner each time that an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true},{"type":"text","text":" instance has been found"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that this will be called both when a new device is found and when the RSSI\/signal strength of a previously discovered device has changed."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"It is possible to use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id"},{"type":"text","text":" parameter as a means to uniquely identify discovered devices."}]}]},{"content":[{"inlineContent":[{"text":"Do not hold reference to stale ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instances; use the most recently reported device instance when connecting to a device later.","type":"text"}],"type":"paragraph"}]}]}]}]}]}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Devices can only be discovered or recalled while your SDK licence is in an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","isActive":true,"type":"reference"},{"type":"text","text":" state; the current value is available via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","isActive":true,"type":"reference"},{"type":"text","text":". Only device types supported by your license can be discovered and connected; the current list of allowed types is available via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"Note","style":"note"},{"type":"paragraph","inlineContent":[{"text":"To use the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"text":":","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Initialize the scanner and check its state in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerInit(_:state:)"}]},{"items":[{"content":[{"inlineContent":[{"text":"After a successful initialization, the state will be ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/IDLE","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"If the state is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE"},{"text":", check ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state"},{"text":" for further details.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"If the scanner has initialized successfully, the scanner can be started using "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)","type":"reference"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"By default, the scanner will search for a period ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","type":"reference"},{"text":", but this interval can be overridden by providing an argument for ","type":"text"},{"code":"scanPeriodMs","type":"codeVoice"},{"text":".","type":"text"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Discovered devices will be reported via a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback"},{"text":" closure. At this stage, it is valid to check a limited number of parameters:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","isActive":true},{"type":"text","text":": Device identifier string"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","type":"reference","isActive":true},{"type":"text","text":": Device signal strength (-127 to 0). Will be 0 for USB connected devices"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType"},{"type":"text","text":": Indicates whether the device was found via Bluetooth or USB connection"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/type","type":"reference"},{"text":": Indicates the specific device type","type":"text"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","isActive":true,"type":"reference"},{"text":": Full name of the device (e.g. ‘Nix Spectro 2’)","type":"text"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device search will run for the specified duration, after which "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerStopped(_:)"},{"type":"text","text":" is called. The device search can also be manually stopped using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/stop()"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"To recall a specific Bluetooth connected device in a later app session, you can use ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/startSearchForId(_:closure:)","type":"reference"},{"text":". This will run the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference"},{"text":" searching for a specific device by its identifier, calling back only once when the device is first found.","type":"text"}]}]}]},{"level":4,"type":"heading","text":"Swift example","anchor":"Swift-example"},{"syntax":"swift","type":"codeListing","code":["import UIKit","import NixUniversalSDK","","class MyViewController: UIViewController, ScannerStateDelegate {","    var scanner: IDeviceScanner? = nil","","    override func viewDidLoad() {","        super.viewDidLoad()","","        \/\/ Do any additional setup after loading the view.","        \/\/ Your existing code here ...","        ","        \/\/ Initialize DeviceScanner","        scanner = DeviceScanner(delegate: self)","    }","","    \/\/ MARK: ScannerStateDelegate","    func onScannerInit(","        _ sender: NixUniversalSDK.IDeviceScanner, ","        state: DeviceScannerState","    ) {        ","        \/\/ Scanner has initialized","        switch state {","        case .IDLE:","            \/\/ Successful initialization","            \/\/ Can start a search now ...","            break","        case .ERROR_LICENSE:","            \/\/ There is an issue with the LicenseManager","            \/\/ Check LicenseManager.state ...","            break","        case .ERROR_BLUETOOTH_PERMISSIONS:","            \/\/ User has denied access to Bluetooth","            \/\/ Handle error ...","            break","        case .ERROR_BLUETOOTH_DISABLED, .ERROR_BLUETOOTH_UNAVAILABLE:","            \/\/ Bluetooth is disabled or not available","            \/\/ Handle error...        ","            break","        default:","            \/\/ Other error ...","            break","        }","    }","","    func onScannerStarted(","        _ sender: NixUniversalSDK.IDeviceScanner","    ) {","        \/\/ Scanner has started","        \/\/ ...","    }","","    func onScannerStopped(","        _ sender: NixUniversalSDK.IDeviceScanner","    ) {","        \/\/ Scanner has stopped","        \/\/ ...","    }","","    \/\/ MARK: DeviceScanner","    func startSearch {","        \/\/ Define callback to be invoked when devices are found","        let callback: DeviceFoundCallback = { device in","            if let device {","                \/\/ Nearby device found","                \/\/ Handle discovery here ...","","                \/\/ Valid to query some parameters now:","                print(\"Found \\(device.name) with id \\(device.id) at RSSI \\(device.rssi)\")","            }","        }","","        \/\/ Start the scanner if it is non-null","        let newState: DeviceScannerState =","            scanner?.start(closure: callback) ?? .COLD","    }","}"]},{"level":4,"type":"heading","text":"Objective-C example","anchor":"Objective-C-example"},{"type":"codeListing","syntax":"objc","code":["#import \"MyViewController.h\"","#import <NixUniversalSDK\/universalsdk.h>","","@interface MyViewController () <ScannerStateDelegate>","","@property (nonatomic, strong) DeviceScannerNullable scanner;","","@end","","@implementation MyViewController","","#pragma mark UIViewController","- (void)viewDidLoad {","    [super viewDidLoad];","    \/\/ Do any additional setup after loading the view.","    ","    \/\/ Initialize DeviceScanner","    self.scanner = [[DeviceScanner alloc] initWithDelegate:self];","}","","#pragma mark ScannerStateDelegate","- (void)onScannerInit:(DeviceScannerNonnull)sender","                state:(enum DeviceScannerState)state {","    \/\/ Scanner has initialized","    switch (state) {","        case DeviceScannerStateIDLE:","            \/\/ Successful initialization","            \/\/ Can start a search now...","            break;","        case DeviceScannerStateERROR_LICENSE:","            \/\/ There is an issue with the LicenseManager","            \/\/ Check LicenseManager.state ...","        case DeviceScannerStateERROR_BLUETOOTH_PERMISSIONS:","            \/\/ User has denied access to Bluetooth","            \/\/ Handle error ...","            break;","        case DeviceScannerStateERROR_BLUETOOTH_DISABLED:","        case DeviceScannerStateERROR_BLUETOOTH_UNAVAILABLE:","            \/\/ Bluetooth is disabled or not available","            \/\/ Handle error...","            break;","        default:","            \/\/ Other error ...","            break;","    }","}","","- (void)onScannerStarted:(DeviceScannerNonnull)sender {","    \/\/ Scanner has started","    \/\/ ...","}","","- (void)onScannerStopped:(DeviceScannerNonnull)sender {","    \/\/ Scanner has stopped","    \/\/ ...","}","","#pragma mark DeviceScanner","- (void) startSearch {","    \/\/ Define closure to be called when devices are found","    DeviceCompatBlock closure = ^(DeviceCompatNullable device) {","        if (device != nil) {","            \/\/ Nearby device found","            \/\/ Handle discovery here ...","            ","            \/\/ Valid to query some parameters now:","            NSLog(@\"Found %@ with id %@ at RSSI %d\",","                  device.name,","                  device.id,","                  (int)device.rssi);","        }","    };","    ","    \/\/ Start the search","    enum DeviceScannerState newState = DeviceScannerStateCOLD;","    if (self.scanner != nil) {","        newState = [self.scanner startWithClosure:closure];","    }","}","@end"]},{"type":"heading","text":"Opening a connection","level":3,"anchor":"Opening-a-connection"},{"type":"paragraph","inlineContent":[{"text":"Once an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"text":" instance has been obtained, a connection can be opened by calling ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","type":"reference","isActive":true},{"text":". Connection state changes are provided via a ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","type":"reference","isActive":true},{"text":".","type":"text"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Implement the "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","type":"reference"},{"type":"text","text":" protocol in your class"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Stop the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","isActive":true},{"text":" before opening a connection, if still running.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"It is safe to call "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/stop()"},{"type":"text","text":" at any time, even if already stopped"}],"type":"paragraph"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Start the connection process using "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"The connection process is asynchronous and "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","isActive":true},{"type":"text","text":" will return immediately. If a connection activity indicator is shown, it can be shown immediately before calling this method."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A call to ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","type":"reference","isActive":true},{"text":" will always result in either the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","type":"reference","isActive":true},{"text":" or ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","type":"reference","isActive":true},{"text":" event being triggered.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Device operations are not possible until the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","isActive":true,"type":"reference"},{"text":" callback is received (successful connection)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the connection process fails, "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)"},{"type":"text","text":" will be called with an appropriate status code indicating the cause of the error."}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","type":"reference"},{"text":" will also be called later whenever the device is disconnected. This can occur normally (i.e. - if the host device calls ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","type":"reference"},{"text":"), or abnormally (i.e. - if the connection is dropped due to an error or low Bluetooth signal strength).","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Your license is linked to a specific allocation of Nix devices and will not operate with devices from another allocation."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"At connection time, the SDK will read an allocation code stored on the Nix device and compare to the license information.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"If this check does not pass, the SDK will contact a Nix authentication server to check if that device serial number is authorized."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If the device cannot be authenticated (i.e. – an unknown allocation code was found and an internet connection is unavailable), the device will be disconnected with the status "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The internet connection is required only once every 30 days – once authorized, this status is saved, and connections can be made offline for this time period.","type":"text"}]}]}],"type":"unorderedList"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"When the user has finished using the device, the connection can be closed using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()"}]}]}]},{"type":"heading","text":"Swift example","level":4,"anchor":"Swift-example"},{"type":"codeListing","syntax":"swift","code":["import UIKit","import NixUniversalSDK","","class MyConnectingViewController: UIViewController, DeviceStateDelegate {","    \/\/ Your existing code here","    \/\/ ...","","    \/\/ Device instance found by the DeviceScanner:","    var device: IDeviceCompat","","    \/\/ Example of calling `connect`","    func connectToDevice() {","        device.connect(self)","    }","","    \/\/ MARK: DeviceStateDelegate","    func onConnected(","        _ sender: NixUniversalSDK.IDeviceCompat","    ) {","        \/\/ Device has connected successfully","        \/\/ Device properties can now be queried","        \/\/ Device commands\/operations can now run","        \/\/ ...","    }","    ","    func onDisconnected(","        _ sender: NixUniversalSDK.IDeviceCompat, ","        status: NixUniversalSDK.DeviceStatus","    ) {","        \/\/ Handle status codes here, if desired in your application","        \/\/ At a minimum should check for ERROR_UNAUTHORIZED status (see notes)","        switch status {","        case .ERROR_UNAUTHORIZED:","            \/\/ Device not authorized for this license UUID","            \/\/ ...","            break","        case .ERROR_LICENSE:","            \/\/ There is an issue with the LicenseManager","            \/\/ Check LicenseManager.state","            \/\/ ...","            break","        case .SUCCESS:","            \/\/ Normal disconnect, triggered by device.disconnect()","            \/\/ ...","            break","        case .ERROR_DROPPED_CONNECTION:","            \/\/ Nix device dropped the connection","            \/\/ ...","            break","        case .ERROR_TIMEOUT:","            \/\/ Connection to Nix device timed out","            \/\/ ...","            break","        case .ERROR_MAX_ATTEMPTS, ","             .ERROR_UNSUPPORTED_DEVICE, ","             .ERROR_INTERNAL:","            \/\/ Other internal errors","            \/\/ ...","            break","        default:","            break","        }","    }","","    func onBatteryStateChanged(","        _ sender: NixUniversalSDK.IDeviceCompat, ","        newState: NSNumber","    ) {","        \/\/ Battery level has updated","        \/\/ ...","        print(\"Battery level has updated to \\(newState)\")","    }","","    func onExtPowerStateChanged(","        _ sender: NixUniversalSDK.IDeviceCompat, ","        newState: Bool","    ) {","        \/\/ External power has been connected or disconnected","        \/\/ ...","        print(\"External power connected is now \\(newState)\")","    }","}"]},{"type":"heading","text":"Objective-C example","level":4,"anchor":"Objective-C-example"},{"type":"codeListing","syntax":"objc","code":["#import \"MyConnectingViewController.h\"","#import <NixUniversalSDK\/universalsdk.h>","","@interface MyConnectingViewController () <DeviceStateDelegate>","","\/\/ Device instance found by the DeviceScanner","@property(nonatomic, strong) DeviceCompatNonnull device;","","@end","","@implementation MyConnectingViewController","","\/\/ Your existing code here","\/\/ ...","","\/\/ Example of calling `connect`","- (void) connectToDevice {","    [self.device connect:self];","}","","#pragma mark DeviceStateDelegate","- (void)onConnected:(DeviceCompatNonnull)sender {","    \/\/ Device has connected successfully","    \/\/ Device properties can now be queried","    \/\/ Device commands\/operations can now run","    \/\/ ...","}","","- (void)onDisconnected:(DeviceCompatNonnull)sender","                status:(enum DeviceStatus)status {","    \/\/ Handle status codes here, if desired in your application","    \/\/ At a minimum should check for ERROR_UNAUTHORIZED status (see notes)","    switch (status) {","        case DeviceStatusERROR_UNAUTHORIZED:","            \/\/ Device not authorized for this license UUID","            \/\/ ...","            break;","        case DeviceStatusERROR_LICENSE:","            \/\/ There is an issue with the LicenseManager","            \/\/ Check LicenseManager.state","            \/\/ ...","            break;","        case DeviceStatusSUCCESS:","            \/\/ Normal disconnect, triggered by [device disconnect];","            \/\/ ...","            break;","        case DeviceStatusERROR_DROPPED_CONNECTION:","            \/\/ Nix device dropped the connection","            \/\/ ...","            break;","        case DeviceStatusERROR_TIMEOUT:","            \/\/ Connection to Nix device timed out","            \/\/ ...","            break;","        case DeviceStatusERROR_MAX_ATTEMPTS:","        case DeviceStatusERROR_UNSUPPORTED_DEVICE:","        case DeviceStatusERROR_INTERNAL:","            \/\/ Other internal errors","            \/\/ ...","            break;","    }","}","","- (void)onBatteryStateChanged:(DeviceCompatNonnull)sender","                     newState:(NSNumber * _Nonnull)newState {","    \/\/ Battery level has updated","    \/\/ ...","    NSLog(@\"Battery level has updated to %@\", newState);","}","","- (void)onExtPowerStateChanged:(DeviceCompatNonnull)sender","                      newState:(BOOL)newState {","    \/\/ External power has been connected or disconnected","    \/\/ ...","    NSString* stateString = newState ? @\"true\" : @\"false\";","    NSLog(@\"External power connected is now %@\", stateString);","}","","@end"]},{"type":"heading","text":"Next Steps","level":2,"anchor":"Next-Steps"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","type":"reference"}]}]}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"title":"DeviceStateDelegate","navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","abstract":[{"text":"Definition for a callback from an ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/id":{"abstract":[{"text":"Unique identifier for this device","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/id","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"id","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/example-apps":{"abstract":[{"text":"Explore source code for demo iOS and macOS applications","type":"text"}],"kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","role":"article","type":"topic","title":"Example Applications","url":"\/documentation\/nixuniversalsdk\/example-apps"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/startSearchForId(_:closure:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/startSearchForId(_:closure:)","url":"\/documentation\/nixuniversalsdk\/idevicescanner\/startsearchforid(_:closure:)","kind":"symbol","abstract":[{"type":"text","text":"Starts a search for a specific Nix device using Bluetooth. The search will run until the specified device is found, or until "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_SINGLE_DEVICE_PERIOD_MS"},{"type":"text","text":" elapses, whichever is shorter. Invoked with a "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" result when a search times out and device was not found."}],"role":"symbol","navigatorTitle":[{"text":"startSearchForId:withClosure:","kind":"identifier"}],"title":"startSearchForId(_:closure:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSearchForId"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": "},{"preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","kind":"typeIdentifier","text":"DeviceFoundCallback"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","kind":"typeIdentifier","text":"DeviceScannerState"}],"type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onConnected(_:)":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/onconnected(_:)","required":true,"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Called when the Nix device has completed the connection process and is now idle."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"onConnected:","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onConnected(_:)","title":"onConnected(_:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/type":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Type for this device","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DeviceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","kind":"typeIdentifier"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/type","title":"type"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier","text":"LicenseManagerState"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","abstract":[{"type":"text","text":"Describes the current state of the  "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"type":"text","text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE"},{"type":"text","text":")"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanager\/state","title":"state","navigatorTitle":[{"kind":"identifier","text":"state"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner/DEFAULT_GENERAL_SCAN_PERIOD_MS":{"title":"DEFAULT_GENERAL_SCAN_PERIOD_MS","url":"\/documentation\/nixuniversalsdk\/devicescanner\/default_general_scan_period_ms","abstract":[{"type":"text","text":"Scan period in milliseconds (20000) used when no time period is provided to "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)","isActive":true}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_GENERAL_SCAN_PERIOD_MS"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate/onScannerStopped(_:)":{"abstract":[{"type":"text","text":"Called when an "},{"type":"codeVoice","code":"IDeviceScanner"},{"type":"text","text":" has stopped searching"}],"type":"topic","title":"onScannerStopped(_:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onScannerStopped","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner","text":"IDeviceScanner","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerStopped(_:)","role":"symbol","url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate\/onscannerstopped(_:)","navigatorTitle":[{"text":"onScannerStopped:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/disconnect()":{"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/disconnect()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnect"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"disconnect"}],"abstract":[{"type":"text","text":"Disconnect from this Nix device, or cancel a connection attempt currently in progress."}],"required":true,"title":"disconnect()","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/disconnect()"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate/onDisconnected(_:status:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate\/onDisconnected(_:status:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onDisconnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceCompat","text":"IDeviceCompat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceStatus","text":"DeviceStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","required":true,"title":"onDisconnected(_:status:)","url":"\/documentation\/nixuniversalsdk\/devicestatedelegate\/ondisconnected(_:status:)","abstract":[{"text":"Called when the Nix device has disconnected from the host.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"onDisconnected:status:","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/name":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/name","url":"\/documentation\/nixuniversalsdk\/idevicecompat\/name","title":"name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Name for this device"}],"required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"url":"\/documentation\/nixuniversalsdk\/wrapper","title":"Wrapper for Usage in C\/C++","abstract":[{"text":"Review an example project which provides a C\/C++ interface for macOS applications","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","kind":"article","role":"article","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ACTIVE"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The license has activated successfully and Nix Universal SDK functions are available."}],"kind":"symbol","title":"LicenseManagerState.ACTIVE"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"role":"article","abstract":[{"type":"text","text":"Review the changes made in this version of the library"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","title":"Release Notes","url":"\/documentation\/nixuniversalsdk\/release-notes","type":"topic","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner":{"navigatorTitle":[{"kind":"identifier","text":"DeviceScanner"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","abstract":[{"type":"text","text":"Class used to discover nearby Nix devices"}],"url":"\/documentation\/nixuniversalsdk\/devicescanner","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceScanner"}],"title":"DeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/connect(delegate:)":{"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/connect(delegate:)","title":"connect(delegate:)","navigatorTitle":[{"text":"connect:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)DeviceStateDelegate","text":"DeviceStateDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Open a connection to this Nix device. This operation is asynchronous and this method returns immediately. Status of this operation is updated via the provided "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},{"type":"text","text":" callback."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/connect(delegate:)","role":"symbol","required":true},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ScannerStateDelegate","kind":"identifier"}],"title":"ScannerStateDelegate","role":"symbol","url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate","abstract":[{"text":"Protocol definition for a callback to be invoked when an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","isActive":true,"type":"reference"},{"text":" starts or stops a search.","type":"text"}],"navigatorTitle":[{"text":"ScannerStateDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ScannerStateDelegate/onScannerInit(_:state:)":{"abstract":[{"type":"text","text":"Called when the "},{"type":"codeVoice","code":"IDeviceScanner"},{"type":"text","text":" has initialized. Check "},{"type":"codeVoice","code":"state"},{"type":"text","text":" to determine success or failure code."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ScannerStateDelegate\/onScannerInit(_:state:)","type":"topic","kind":"symbol","title":"onScannerInit(_:state:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onScannerInit","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IDeviceScanner","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDeviceScanner","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"state","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","kind":"typeIdentifier","text":"DeviceScannerState"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onScannerInit:state:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/scannerstatedelegate\/onscannerinit(_:state:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"role":"symbol","kind":"symbol","abstract":[{"text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager","navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"title":"LicenseManager","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManager","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/start(scanPeriodMs:closure:)":{"abstract":[{"type":"text","text":"Starts a search for nearby Nix devices using Bluetooth for a selected time interval. If no timeout interval is specified, the search will run for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_GENERAL_SCAN_PERIOD_MS"},{"type":"text","text":"."}],"title":"start(scanPeriodMs:closure:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"scanPeriodMs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"closure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:15NixUniversalSDK19DeviceFoundCallbacka","text":"DeviceFoundCallback"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceScannerState","text":"DeviceScannerState"}],"navigatorTitle":[{"kind":"identifier","text":"startForPeriodMs:withClosure:"}],"required":true,"url":"\/documentation\/nixuniversalsdk\/idevicescanner\/start(scanperiodms:closure:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/start(scanPeriodMs:closure:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScanner/DEFAULT_SINGLE_DEVICE_PERIOD_MS":{"role":"symbol","title":"DEFAULT_SINGLE_DEVICE_PERIOD_MS","abstract":[{"type":"text","text":"Scan period in milliseconds (10000) used when no time period is provided to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/startSearchForId(_:closure:)"}],"kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescanner\/default_single_device_period_ms","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"DEFAULT_SINGLE_DEVICE_PERIOD_MS"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner\/DEFAULT_SINGLE_DEVICE_PERIOD_MS"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"abstract":[{"type":"text","text":"Take measurements, set device options, and query device properties"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","role":"article","title":"Device Operations","type":"topic","url":"\/documentation\/nixuniversalsdk\/device-operations","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_UNAUTHORIZED":{"abstract":[{"text":"The device connection attempt was cancelled because the specified device was not authorized for this build of the Nix SDK. Check that the device allocation code and\/or serial number is expected to be authorized for this build.","type":"text"}],"role":"symbol","url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_unauthorized","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_UNAUTHORIZED"}],"title":"DeviceStatus.ERROR_UNAUTHORIZED","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_UNAUTHORIZED"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_UNAUTHORIZED"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceFoundCallback":{"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceFoundCallback"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceFoundCallback"}],"kind":"symbol","title":"DeviceFoundCallback","abstract":[{"text":"Definition for a closure invoked when an ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner","type":"reference","isActive":true},{"text":" has discovered a supported Nix device","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicefoundcallback","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceFoundCallback"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceCompat"}],"kind":"symbol","abstract":[{"text":"Protocol describing the supported properties and methods for a Nix device. ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","type":"reference","isActive":true},{"text":" objects are found nearby using the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceCompat"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","title":"IDeviceCompat","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner":{"url":"\/documentation\/nixuniversalsdk\/idevicescanner","title":"IDeviceScanner","kind":"symbol","abstract":[{"text":"Protocol implemented by the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScanner","type":"reference","isActive":true}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IDeviceScanner"}],"navigatorTitle":[{"kind":"identifier","text":"IDeviceScanner"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/ERROR_LICENSE":{"navigatorTitle":[{"kind":"identifier","text":"DeviceScannerStateERROR_LICENSE"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/ERROR_LICENSE","type":"topic","title":"DeviceScannerState.ERROR_LICENSE","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/error_license","abstract":[{"text":"Bluetooth scanner could not start due to a problem with the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"reference"},{"text":". Check ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","type":"reference"},{"text":" for details.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/rssi":{"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/rssi","role":"symbol","title":"rssi","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rssi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"rssi"}],"abstract":[{"type":"text","text":"Signal strength for this device"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/rssi","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceScannerState/IDLE":{"title":"DeviceScannerState.IDLE","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceScannerState\/IDLE","role":"symbol","navigatorTitle":[{"text":"DeviceScannerStateIDLE","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IDLE","kind":"identifier"}],"abstract":[{"type":"text","text":"Bluetooth scanner is not actively searching for devices."}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/devicescannerstate\/idle"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/allowedDeviceTypes-4f98s":{"kind":"symbol","title":"allowedDeviceTypes","abstract":[{"type":"text","text":"Set of device types supported by the current license. Available in Swift only."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/allowedDeviceTypes-4f98s","url":"\/documentation\/nixuniversalsdk\/licensemanager\/alloweddevicetypes-4f98s","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedDeviceTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType"},{"kind":"text","text":">"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"url":"\/documentation\/nixuniversalsdk\/add-to-xcode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","title":"Adding to Your Xcode Project","abstract":[{"type":"text","text":"Add the library bundle to your project and declare peripheral uses"}],"kind":"article","type":"topic","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","type":"topic","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceScanner/stop()":{"navigatorTitle":[{"text":"stop","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stop()","required":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceScanner\/stop()","url":"\/documentation\/nixuniversalsdk\/idevicescanner\/stop()","abstract":[{"text":"Stops a Bluetooth search if one is currently running.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","role":"article","abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}],"title":"Activating the SDK License","type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/activating-license"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/IDeviceCompat/interfaceType":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat\/interfaceType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"interfaceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InterfaceType","preciseIdentifier":"c:@M@NixUniversalSDK@E@InterfaceType"}],"title":"interfaceType","abstract":[{"type":"text","text":"Interface \/ connection type for this device"}],"url":"\/documentation\/nixuniversalsdk\/idevicecompat\/interfacetype","required":true,"navigatorTitle":[{"kind":"identifier","text":"interfaceType"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":[{"title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"anchor":"Getting-Started","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":"DeviceStateDelegate","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceStateDelegate"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","op":"replace"},{"value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","op":"replace"},{"value":"id","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/title","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1id\/fragments","op":"replace"},{"value":"startSearchForId:withClosure:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1startSearchForId(_:closure:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startSearchForId:withClosure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1startSearchForId(_:closure:)\/fragments","op":"replace"},{"value":"onConnected:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onConnected(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConnected:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onConnected(_:)\/fragments","op":"replace"},{"value":"type","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1type\/title","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1type\/fragments","op":"replace"},{"value":"state","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title","op":"replace"},{"value":[{"kind":"identifier","text":"state"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments","op":"replace"},{"value":"onScannerStopped:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerStopped(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onScannerStopped:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerStopped(_:)\/fragments","op":"replace"},{"value":"disconnect","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"disconnect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1disconnect()\/fragments","op":"replace"},{"value":"onDisconnected:status:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onDisconnected(_:status:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onDisconnected:status:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate~1onDisconnected(_:status:)\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/title","op":"replace"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1name\/fragments","op":"replace"},{"value":"LicenseManagerStateACTIVE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title","op":"replace"},{"value":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","op":"replace"},{"value":"DeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceScanner"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/fragments","op":"replace"},{"value":[{"text":"DeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScanner\/navigatorTitle","op":"replace"},{"value":"connect:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1connect(delegate:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"connect:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1connect(delegate:)\/fragments","op":"replace"},{"value":"ScannerStateDelegate","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ScannerStateDelegate"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/fragments","op":"replace"},{"value":[{"text":"ScannerStateDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate\/navigatorTitle","op":"replace"},{"value":"onScannerInit:state:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerInit(_:state:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onScannerInit:state:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ScannerStateDelegate~1onScannerInit(_:state:)\/fragments","op":"replace"},{"value":"LicenseManager","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","op":"replace"},{"value":[{"text":"LicenseManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","op":"replace"},{"value":[{"text":"LicenseManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","op":"replace"},{"value":"startForPeriodMs:withClosure:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(scanPeriodMs:closure:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startForPeriodMs:withClosure:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1start(scanPeriodMs:closure:)\/fragments","op":"replace"},{"value":"DeviceStatusERROR_UNAUTHORIZED","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/title","op":"replace"},{"value":[{"text":"DeviceStatusERROR_UNAUTHORIZED","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_UNAUTHORIZED\/fragments","op":"replace"},{"value":"IDeviceCompat","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"IDeviceCompat"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/fragments","op":"replace"},{"value":[{"text":"IDeviceCompat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat\/navigatorTitle","op":"replace"},{"value":"IDeviceScanner","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/title","op":"replace"},{"value":[{"text":"IDeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/fragments","op":"replace"},{"value":[{"text":"IDeviceScanner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner\/navigatorTitle","op":"replace"},{"value":"DeviceScannerStateERROR_LICENSE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceScannerStateERROR_LICENSE"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1ERROR_LICENSE\/fragments","op":"replace"},{"value":"rssi","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/title","op":"replace"},{"value":[{"text":"rssi","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1rssi\/fragments","op":"replace"},{"value":"DeviceScannerStateIDLE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1IDLE\/title","op":"replace"},{"value":[{"text":"DeviceScannerStateIDLE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceScannerState~1IDLE\/fragments","op":"replace"},{"value":"stop","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1stop()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceScanner~1stop()\/fragments","op":"replace"},{"value":"interfaceType","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/title","op":"replace"},{"value":[{"text":"interfaceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1IDeviceCompat~1interfaceType\/fragments","op":"replace"}]}]}