{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Explore source code for demo iOS and macOS applications"}],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Two example applications and their complete source code are provided with the Nix Universal SDK download, available "},{"identifier":"https:\/\/www.nixsensor.com\/sdk-ios","type":"reference","isActive":true},{"type":"text","text":". Both applications demonstrate:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Activating and displaying license information","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Device discovery on Bluetooth and USB interfaces"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Opening and closing a connection to a device"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Displaying additional device info (serial number, battery level, etc.)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Toggling device options (haptic feedback, RGB feedback, etc.)","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Taking measurements","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Obtaining colorimetry and spectral data from measurements"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Performing in-field calibration on the provided reference tile","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Displaying additional measurement information (temperature, scan settings, etc.)","type":"text"}]}]}]},{"type":"heading","text":"iOS application","anchor":"iOS-application","level":3},{"type":"paragraph","inlineContent":[{"text":"To run the iOS example:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Open the ‘example-ios\/Nix Example.xcodeproj’ Xcode Project","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Update the license information in "},{"code":"LicenseKey.swift","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Build and run","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"ios_example.png"}]},{"type":"heading","text":"macOS application","anchor":"macOS-application","level":3},{"type":"paragraph","inlineContent":[{"text":"To run the macOS example:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Open the ‘example-macos\/Nix Example.xcodeproj’ Xcode Project","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Update the license information in "},{"type":"codeVoice","code":"LicenseKey.swift"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Build and run"}],"type":"paragraph"}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"macos_example.png"}]},{"type":"heading","text":"Next Steps","anchor":"Next-Steps","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","isActive":true}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"metadata":{"title":"Example Applications","modules":[{"name":"NixUniversalSDK"}],"role":"article","roleHeading":"Article"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/example-apps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/example-apps"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/example-apps","interfaceLanguage":"swift"},"sections":[],"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"],"generated":true,"title":"Getting Started","anchor":"Getting-Started"}],"references":{"https://www.nixsensor.com/sdk-ios":{"url":"https:\/\/www.nixsensor.com\/sdk-ios","type":"link","titleInlineContent":[{"type":"text","text":"online"}],"title":"online","identifier":"https:\/\/www.nixsensor.com\/sdk-ios"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","type":"topic","abstract":[{"text":"Query measurement values including colorimetry, spectral reflectance, and density","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/wrapper":{"url":"\/documentation\/nixuniversalsdk\/wrapper","title":"Wrapper for Usage in C\/C++","abstract":[{"text":"Review an example project which provides a C\/C++ interface for macOS applications","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper","kind":"article","role":"article","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/activating-license":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","role":"article","abstract":[{"type":"text","text":"Enable Nix device functions with your license code"}],"title":"Activating the SDK License","type":"topic","kind":"article","url":"\/documentation\/nixuniversalsdk\/activating-license"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/device-operations":{"abstract":[{"type":"text","text":"Take measurements, set device options, and query device properties"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","role":"article","title":"Device Operations","type":"topic","url":"\/documentation\/nixuniversalsdk\/device-operations","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/add-to-xcode":{"url":"\/documentation\/nixuniversalsdk\/add-to-xcode","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","title":"Adding to Your Xcode Project","abstract":[{"type":"text","text":"Add the library bundle to your project and declare peripheral uses"}],"kind":"article","type":"topic","role":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"role":"article","abstract":[{"type":"text","text":"Review the changes made in this version of the library"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","title":"Release Notes","url":"\/documentation\/nixuniversalsdk\/release-notes","type":"topic","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/discovering-connecting":{"type":"topic","abstract":[{"text":"Use the device scanner to discover Nix devices and open a connection","type":"text"}],"kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","url":"\/documentation\/nixuniversalsdk\/discovering-connecting","role":"article","title":"Discovering and Connecting to Nix Devices"},"macos_example.png":{"alt":"macOS Demo Screenshot","type":"image","variants":[{"url":"\/images\/com.nixsensor.universalsdk\/macos_example@3x.png","traits":["3x","light"]}],"identifier":"macos_example.png"},"ios_example.png":{"alt":"iOS Demo Screenshot","type":"image","variants":[{"url":"\/images\/com.nixsensor.universalsdk\/ios_example@3x.png","traits":["3x","light"]}],"identifier":"ios_example.png"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK#Additional-Support":{"abstract":[],"kind":"section","title":"Additional Support","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK#Additional-Support","url":"\/documentation\/nixuniversalsdk#Additional-Support","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"anchor":"Getting-Started","title":"Getting Started","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/add-to-xcode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/activating-license","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/discovering-connecting","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/device-operations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/wrapper"]}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}