{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/BLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/UNDEFINED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/USB_CDC"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/name"],"anchor":"Instance-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceType","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"metadata":{"modules":[{"name":"NixUniversalSDK"}],"role":"symbol","externalID":"c:@M@NixUniversalSDK@E@InterfaceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InterfaceType"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"InterfaceType"}],"title":"InterfaceType","symbolKind":"enum"},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/interfacetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/interfacetype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/nixuniversalsdk\/interfacetype\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/init(rawValue:)":{"kind":"symbol","role":"symbol","abstract":[],"title":"init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/interfacetype\/init(rawvalue:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/BLE":{"title":"InterfaceType.BLE","url":"\/documentation\/nixuniversalsdk\/interfacetype\/ble","role":"symbol","kind":"symbol","abstract":[{"text":"Device connects via Bluetooth (BLE) interface.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/BLE","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BLE","kind":"identifier"}],"navigatorTitle":[{"text":"InterfaceTypeBLE","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/Equatable-Implementations","kind":"article","url":"\/documentation\/nixuniversalsdk\/interfacetype\/equatable-implementations","type":"topic"},"doc://com.nixsensor.universalsdk/SY":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceType","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the supported connection interface types for Nix devices."}],"navigatorTitle":[{"kind":"identifier","text":"InterfaceType"}],"title":"InterfaceType","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","url":"\/documentation\/nixuniversalsdk\/interfacetype","kind":"symbol","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/UNDEFINED":{"kind":"symbol","abstract":[{"text":"Device does not have a defined connection type.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UNDEFINED"}],"navigatorTitle":[{"kind":"identifier","text":"InterfaceTypeUNDEFINED"}],"type":"topic","title":"InterfaceType.UNDEFINED","url":"\/documentation\/nixuniversalsdk\/interfacetype\/undefined","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/UNDEFINED"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/name":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/name","type":"topic","url":"\/documentation\/nixuniversalsdk\/interfacetype\/name","kind":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[{"text":"String representation of this ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType","isActive":true,"type":"reference"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/InterfaceType/USB_CDC":{"title":"InterfaceType.USB_CDC","kind":"symbol","role":"symbol","url":"\/documentation\/nixuniversalsdk\/interfacetype\/usb_cdc","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/USB_CDC","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"USB_CDC"}],"navigatorTitle":[{"kind":"identifier","text":"InterfaceTypeUSB_CDC"}],"abstract":[{"type":"text","text":"Device connects via USB interface."}],"type":"topic"},"doc://com.nixsensor.universalsdk/SQ":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"InterfaceType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"InterfaceType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"InterfaceType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/BLE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/UNDEFINED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/InterfaceType\/USB_CDC"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InterfaceType","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1BLE\/title","value":"InterfaceTypeBLE","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1BLE\/fragments","value":[{"text":"InterfaceTypeBLE","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/title","value":"InterfaceType","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/fragments","value":[{"kind":"identifier","text":"InterfaceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType\/navigatorTitle","value":[{"text":"InterfaceType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1UNDEFINED\/title","value":"InterfaceTypeUNDEFINED","op":"replace"},{"value":[{"text":"InterfaceTypeUNDEFINED","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1UNDEFINED\/fragments"},{"value":"InterfaceTypeUSB_CDC","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1USB_CDC\/title"},{"value":[{"text":"InterfaceTypeUSB_CDC","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1InterfaceType~1USB_CDC\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}