{"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interval","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interpolate(lT:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)"],"anchor":"Instance-Methods","generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"},"metadata":{"modules":[{"name":"NixUniversalSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}],"title":"ISpectralData","symbolKind":"protocol","roleHeading":"Protocol","role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(pl)ISpectralData"},"sections":[],"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"],"type":"conformingTypes","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/ispectraldata"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}]}]},{"kind":"mentions","mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"]}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol describing spectral data obtained from a measurement"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/handling-measurements":{"url":"\/documentation\/nixuniversalsdk\/handling-measurements","role":"article","abstract":[{"type":"text","text":"Query measurement values including colorimetry, spectral reflectance, and density"}],"type":"topic","title":"Handling Measurement Data","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/handling-measurements"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(reference:)":{"required":true,"title":"toRgbValue(reference:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reference"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForReference:"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(reference:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/mode":{"title":"mode","navigatorTitle":[{"kind":"identifier","text":"mode"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/mode","abstract":[{"text":"Scan mode for this measurement.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/mode","kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/value":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"required":true,"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Spectral reflectance values. Each entry "},{"code":"i","type":"codeVoice"},{"text":" in this array corresponds to a wavelength value in ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","isActive":true},{"text":" at the same index.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":">","kind":"text"}],"title":"value","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/value"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/interpolate(lT:)":{"required":true,"title":"interpolate(lT:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interpolate(lT:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"interpolate","kind":"identifier"},{"kind":"text","text":"("},{"text":"lT","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"interpolateAtLt:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Provides an interpolated reflectance value at a specified wavelength value using natural cubic spines. The cubic splines are evaluated at the points specified by "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"},{"type":"text","text":". Interpolated values are evaluated using natural cubic splines."}],"kind":"symbol","type":"topic","url":"\/documentation\/nixuniversalsdk\/ispectraldata\/interpolate(lt:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralData"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","title":"SpectralData","abstract":[{"text":"Class describing spectral data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/lambda":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/lambda","abstract":[{"text":"Wavelength values. Each entry ","type":"text"},{"code":"i","type":"codeVoice"},{"text":" in this array corresponds to a spectral value in ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value","isActive":true,"type":"reference"},{"text":" at the same index.","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","navigatorTitle":[{"kind":"identifier","text":"lambda"}],"title":"lambda","type":"topic","required":true,"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lambda","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/interval":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interval","type":"topic","title":"interval","kind":"symbol","abstract":[{"type":"text","text":"Wavelength spacing (eg - 10 nm)"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"interval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"required":true,"role":"symbol","navigatorTitle":[{"text":"interval","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/interval"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toColorData(reference:type:)":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(reference:type:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"required":true,"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is "},{"code":"nil","type":"codeVoice"},{"text":" if an invalid white point is specified.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"toColorData(reference:type:)","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(reference:type:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toColorData(illuminant:observer:type:)":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/tocolordata(illuminant:observer:type:)","abstract":[{"text":"Provides color data from this measurement for the specified illuminant and observer white point. Result is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if an invalid white point is specified."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(illuminant:observer:type:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"title":"toColorData(illuminant:observer:type:)","type":"topic","required":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toColorData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","text":"Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","text":"IColorData"},{"kind":"text","text":"?"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toRgbValue(illuminant:observer:)":{"title":"toRgbValue(illuminant:observer:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/torgbvalue(illuminant:observer:)","abstract":[{"type":"text","text":"Provides an sRGB value for this measurement for the specified illuminant and observer white point. Result is "},{"type":"codeVoice","code":"nil"},{"text":" if the specified white point is not available for this measurement.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Illuminant","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"text":", ","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Observer","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">?","kind":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","title":"ISpectralData","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData/toDensityData(status:)":{"required":true,"title":"toDensityData(status:)","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toDensityData(status:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toDensityData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"IDensityData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"toDensityDataForStatus:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Provides absolute density values for this measurement for the specified density status evaluated as per ISO 5-3:2009.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/ispectraldata\/todensitydata(status:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ISpectralData","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interval","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/lambda","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/value"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/interpolate(lT:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData\/toRgbValue(reference:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(reference:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1mode\/title","value":"mode"},{"op":"replace","value":[{"kind":"identifier","text":"mode"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1mode\/fragments"},{"op":"replace","value":"value","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/title"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1value\/fragments"},{"value":"interpolateAtLt:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interpolate(lT:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interpolateAtLt:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interpolate(lT:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","op":"replace","value":"SpectralData"},{"op":"replace","value":[{"text":"SpectralData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SpectralData"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle"},{"op":"replace","value":"lambda","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1lambda\/fragments","op":"replace","value":[{"text":"lambda","kind":"identifier"}]},{"value":"interval","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interval\/title","op":"replace"},{"value":[{"kind":"identifier","text":"interval"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1interval\/fragments","op":"replace"},{"value":"toColorDataForReference:andType:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(reference:type:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toColorDataForReference:andType:"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(reference:type:)\/fragments"},{"value":"toColorDataForIlluminant:andObserver:andType:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(illuminant:observer:type:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toColorData(illuminant:observer:type:)\/fragments"},{"value":"toRgbValueForIlluminant:andObserver:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForIlluminant:andObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toRgbValue(illuminant:observer:)\/fragments"},{"value":"ISpectralData","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title"},{"value":[{"kind":"identifier","text":"ISpectralData"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments"},{"value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toDensityData(status:)\/title","op":"replace","value":"toDensityDataForStatus:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData~1toDensityData(status:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toDensityDataForStatus:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}