{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH","doc:\/\/com.nixsensor.universalsdk\/SY"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LicenseManagerState","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.2.0"}]}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState"},"metadata":{"title":"LicenseManagerState","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseManagerState","kind":"identifier"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"LicenseManagerState"}],"symbolKind":"enum","externalID":"c:@M@NixUniversalSDK@E@LicenseManagerState","modules":[{"name":"NixUniversalSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/licensemanagerstate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Enum describing the possible states of the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"reference","isActive":true},{"text":".","type":"text"}],"kind":"symbol","sections":[],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_BAD_SIGNATURE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_EXPIRED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_INVALID_OPTIONS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/INACTIVE"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/init(rawValue:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/name"],"generated":true},{"generated":true,"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/fromInt(_:)"],"title":"Type Methods","anchor":"Type-Methods"},{"identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/Equatable-Implementations","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState":{"role":"symbol","title":"LicenseManagerState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LicenseManagerState","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the possible states of the "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true},{"text":".","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate","navigatorTitle":[{"text":"LicenseManagerState","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","type":"topic"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_LICENSE_EXPIRED":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE_EXPIRED"}],"title":"LicenseManagerState.ERROR_LICENSE_EXPIRED","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_EXPIRED","navigatorTitle":[{"text":"LicenseManagerStateERROR_LICENSE_EXPIRED","kind":"identifier"}],"type":"topic","abstract":[{"text":"The license has expired and is no longer valid. Contact the Nix SDK support team.","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_expired","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_LICENSE_BAD_SIGNATURE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_BAD_SIGNATURE","title":"LicenseManagerState.ERROR_LICENSE_BAD_SIGNATURE","kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_bad_signature","type":"topic","abstract":[{"text":"The license has failed to activate because the signature was invalid. Verify that the correct  options and signature were used when calling ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","type":"reference"},{"text":". Contact the Nix SDK support team if this error persists.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_INTERNAL":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ERROR_INTERNAL","kind":"identifier"}],"title":"LicenseManagerState.ERROR_INTERNAL","kind":"symbol","abstract":[{"text":"An unknown error occurred when activating the license. Contact the Nix SDK support team.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_internal","navigatorTitle":[{"text":"LicenseManagerStateERROR_INTERNAL","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_INTERNAL"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/INACTIVE":{"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/inactive","type":"topic","abstract":[{"type":"text","text":"The license has not been activated yet. Activate the license using "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"INACTIVE","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseManagerStateINACTIVE","kind":"identifier"}],"kind":"symbol","title":"LicenseManagerState.INACTIVE","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/INACTIVE","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ERROR_LICENSE_INVALID_OPTIONS":{"type":"topic","title":"LicenseManagerState.ERROR_LICENSE_INVALID_OPTIONS","abstract":[{"type":"text","text":"The license failed to activate because the options string was invalid. Contact the Nix SDK support team."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_INVALID_OPTIONS"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_LICENSE_INVALID_OPTIONS"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_INVALID_OPTIONS","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/error_license_invalid_options","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/name":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/name","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/name","abstract":[{"type":"text","text":"String representation of this "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature"}],"role":"symbol","kind":"symbol","title":"name"},"doc://com.nixsensor.universalsdk/SY":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SY","title":"Swift.RawRepresentable"},"doc://com.nixsensor.universalsdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable"},"doc://com.nixsensor.universalsdk/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseFeature":{"role":"symbol","title":"LicenseFeature","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/nixuniversalsdk\/licensefeature","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Enum describing the optional features that can be enabled by the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"type":"text","text":". Feature availability can be queried using "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isFeatureEnabled(_:)","type":"reference"},{"type":"text","text":"."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/Equatable-Implementations","abstract":[],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/equatable-implementations"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/init(rawValue:)":{"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/init(rawValue:)","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/init(rawvalue:)","title":"init(rawValue:)","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/activate(options:signature:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/activate(options:signature:)","url":"\/documentation\/nixuniversalsdk\/licensemanager\/activate(options:signature:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"kind":"text","text":"("},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"signature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","text":"LicenseManagerState","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"activateWithOptions:andSignature:"}],"title":"activate(options:signature:)","abstract":[{"text":"Activates a license. The options and signature parameters must exactly match the values provided in the SDK license. Calling this function invalidates any currently active license.","type":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"url":"\/documentation\/nixuniversalsdk\/licensemanager","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseManager"}],"navigatorTitle":[{"text":"LicenseManager","kind":"identifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","title":"LicenseManager","type":"topic","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/fromInt(_:)":{"abstract":[{"text":"Helper method to find the ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState","isActive":true},{"type":"text","text":" enum that corresponds to an integer value. If an unknown integer value is provided then "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_INTERNAL","isActive":true,"type":"reference"},{"text":" is provided.","type":"text"}],"kind":"symbol","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/fromint(_:)","title":"fromInt(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromInt"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/fromInt(_:)","role":"symbol","type":"topic"},"doc://com.nixsensor.universalsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","title":"Swift.Equatable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/RawRepresentable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","title":"LicenseManagerState.ACTIVE","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ACTIVE"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"abstract":[{"type":"text","text":"The license has activated successfully and Nix Universal SDK functions are available."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"LicenseManagerState","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace"},{"value":[{"text":"LicenseManagerState","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_INTERNAL","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_BAD_SIGNATURE","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_EXPIRED","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ERROR_LICENSE_INVALID_OPTIONS","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/INACTIVE"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManagerState"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/title","value":"LicenseManagerState","op":"replace"},{"value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState\/navigatorTitle","value":[{"text":"LicenseManagerState","kind":"identifier"}],"op":"replace"},{"value":"LicenseManagerStateERROR_LICENSE_EXPIRED","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_EXPIRED\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_EXPIRED\/fragments","value":[{"kind":"identifier","text":"LicenseManagerStateERROR_LICENSE_EXPIRED"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_BAD_SIGNATURE\/title","value":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_BAD_SIGNATURE\/fragments","value":[{"text":"LicenseManagerStateERROR_LICENSE_BAD_SIGNATURE","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_INTERNAL\/title","value":"LicenseManagerStateERROR_INTERNAL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_INTERNAL\/fragments","value":[{"text":"LicenseManagerStateERROR_INTERNAL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1INACTIVE\/title","value":"LicenseManagerStateINACTIVE"},{"value":[{"text":"LicenseManagerStateINACTIVE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1INACTIVE\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_INVALID_OPTIONS\/title","value":"LicenseManagerStateERROR_LICENSE_INVALID_OPTIONS","op":"replace"},{"value":[{"text":"LicenseManagerStateERROR_LICENSE_INVALID_OPTIONS","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ERROR_LICENSE_INVALID_OPTIONS\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/title","value":"LicenseFeature","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"LicenseFeature"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/fragments"},{"value":[{"text":"LicenseFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseFeature\/navigatorTitle","op":"replace"},{"op":"replace","value":"activateWithOptions:andSignature:","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1activate(options:signature:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"activateWithOptions:andSignature:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager"},{"value":[{"kind":"identifier","text":"LicenseManager"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}]},{"value":"LicenseManagerStateACTIVE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LicenseManagerStateACTIVE"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}