{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpectralData","kind":"identifier"}],"platforms":["macOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject","doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","doc:\/\/com.nixsensor.universalsdk\/SQ","doc:\/\/com.nixsensor.universalsdk\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"SpectralData","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@NixUniversalSDK@objc(cs)SpectralData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralData"}],"title":"SpectralData"},"sections":[],"abstract":[{"text":"Class describing spectral data","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/init(lambda:value:mode:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interval","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interpolate(lT:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/nixuniversalsdk\/spectraldata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nixuniversalsdk\/spectraldata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","interfaceLanguage":"swift"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/value":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","url":"\/documentation\/nixuniversalsdk\/spectraldata\/value","kind":"symbol","type":"topic","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/mode":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/mode","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","text":"ScanMode"}],"navigatorTitle":[{"text":"mode","kind":"identifier"}],"title":"mode","url":"\/documentation\/nixuniversalsdk\/spectraldata\/mode","kind":"symbol","type":"topic","abstract":[]},"doc://com.nixsensor.universalsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.nixsensor.universalsdk\/SQ","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/interpolate(lT:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interpolate(lT:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interpolate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lT"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interpolateAtLt:"}],"title":"interpolate(lT:)","url":"\/documentation\/nixuniversalsdk\/spectraldata\/interpolate(lt:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/interval":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interval","type":"topic","title":"interval","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interval"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/interval"},"doc://com.nixsensor.universalsdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.nixsensor.universalsdk/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.nixsensor.universalsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/init(lambda:value:mode:)":{"url":"\/documentation\/nixuniversalsdk\/spectraldata\/init(lambda:value:mode:)","abstract":[],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/init(lambda:value:mode:)","title":"init(lambda:value:mode:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"lambda","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","preciseIdentifier":"s:Sa","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":">, ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"text":"<","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"mode"},{"text":": ","kind":"text"},{"text":"ScanMode","preciseIdentifier":"c:@M@NixUniversalSDK@E@ScanMode","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(illuminant:observer:)":{"title":"toRgbValue(illuminant:observer:)","navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(illuminant:observer:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toRgbValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"illuminant"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant","kind":"typeIdentifier","text":"Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","text":"Observer","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Array","kind":"typeIdentifier","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":">?","kind":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toDensityData(status:)":{"title":"toDensityData(status:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toDensityDataForStatus:"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/todensitydata(status:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toDensityData(status:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toDensityData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"IDensityData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IDensityData"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toRgbValue(reference:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)","type":"topic","title":"toRgbValue(reference:)","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toRgbValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reference","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","text":"ReferenceWhite","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/torgbvalue(reference:)"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/SH":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/lambda":{"title":"lambda","navigatorTitle":[{"text":"lambda","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/lambda","abstract":[],"type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lambda","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sa","text":"Array","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(reference:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reference"},{"text":": ","kind":"text"},{"text":"ReferenceWhite","preciseIdentifier":"c:@M@NixUniversalSDK@E@ReferenceWhite","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ColorType","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier","text":"IColorData"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"toColorDataForReference:andType:","kind":"identifier"}],"title":"toColorData(reference:type:)","url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(reference:type:)","kind":"symbol","type":"topic","abstract":[]},"doc://com.nixsensor.universalsdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.nixsensor.universalsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","title":"ISpectralData","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISpectralData"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData":{"navigatorTitle":[{"kind":"identifier","text":"SpectralData"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralData"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData","title":"SpectralData","abstract":[{"text":"Class describing spectral data","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralData/toColorData(illuminant:observer:type:)":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","type":"topic","title":"toColorData(illuminant:observer:type:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"toColorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"illuminant","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Illuminant","preciseIdentifier":"c:@M@NixUniversalSDK@E@Illuminant"},{"kind":"text","text":", "},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"text":"Observer","preciseIdentifier":"c:@M@NixUniversalSDK@E@Observer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@ColorType","text":"ColorType"},{"text":") -> ","kind":"text"},{"text":"IColorData","preciseIdentifier":"c:@M@NixUniversalSDK@objc(pl)IColorData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"toColorDataForIlluminant:andObserver:andType:"}],"url":"\/documentation\/nixuniversalsdk\/spectraldata\/tocolordata(illuminant:observer:type:)"},"doc://com.nixsensor.universalsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.nixsensor.universalsdk\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SpectralData"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SpectralData","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SpectralData","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interval","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/lambda","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/mode","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/value"],"generated":true},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/interpolate(lT:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(illuminant:observer:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toColorData(reference:type:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toDensityData(status:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(illuminant:observer:)","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralData\/toRgbValue(reference:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.nixsensor.universalsdk\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"],"type":"conformsTo","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SpectralData"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["macOS"]}],"kind":"declarations"}},{"op":"replace","value":"value","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1value\/title"},{"op":"replace","value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1value\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1mode\/title","op":"replace","value":"mode"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1mode\/fragments","value":[{"kind":"identifier","text":"mode"}]},{"value":"interpolateAtLt:","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interpolate(lT:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"interpolateAtLt:"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interpolate(lT:)\/fragments"},{"value":"interval","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interval\/title"},{"value":[{"text":"interval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1interval\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/title","value":"toRgbValueForIlluminant:andObserver:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(illuminant:observer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toRgbValueForIlluminant:andObserver:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toDensityData(status:)\/title","value":"toDensityDataForStatus:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toDensityData(status:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toDensityDataForStatus:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/title","value":"toRgbValueForReference:"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toRgbValue(reference:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toRgbValueForReference:","kind":"identifier"}]},{"value":"lambda","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1lambda\/title"},{"value":[{"text":"lambda","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1lambda\/fragments"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/title","value":"toColorDataForReference:andType:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(reference:type:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"toColorDataForReference:andType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"kind":"identifier","text":"ISpectralData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ISpectralData"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/title","value":"SpectralData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/fragments","value":[{"text":"SpectralData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData\/navigatorTitle","value":[{"kind":"identifier","text":"SpectralData"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/title","value":"toColorDataForIlluminant:andObserver:andType:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1SpectralData~1toColorData(illuminant:observer:type:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"toColorDataForIlluminant:andObserver:andType:","kind":"identifier"}],"op":"replace"}]}]}