{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNonnull"},"metadata":{"symbolKind":"typealias","navigatorTitle":[{"text":"SpectralDataNonnull","kind":"identifier"}],"modules":[{"name":"NixUniversalSDK"}],"externalID":"c:TypeAliases.h@T@SpectralDataNonnull","title":"SpectralDataNonnull","roleHeading":"Type Alias","role":"symbol","fragments":[{"kind":"identifier","text":"SpectralDataNonnull"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:Qo@M@NixUniversalSDK@objc(pl)ISpectralData","text":"id<ISpectralData>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SpectralDataNonnull","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["macOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/spectraldatanonnull"]}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Non-null instance of an "},{"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","isActive":true},{"type":"text","text":" object"}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/ISpectralData":{"url":"\/documentation\/nixuniversalsdk\/ispectraldata","type":"topic","title":"ISpectralData","kind":"symbol","abstract":[{"text":"Protocol describing spectral data obtained from a measurement","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISpectralData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ISpectralData"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","type":"topic","abstract":[{"text":"A library to allow integration of Nix devices into third-party iOS and macOS applications.","type":"text"}],"url":"\/documentation\/nixuniversalsdk","role":"collection","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/SpectralDataNonnull":{"url":"\/documentation\/nixuniversalsdk\/spectraldatanonnull","title":"SpectralDataNonnull","abstract":[{"text":"Non-null instance of an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/ISpectralData"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/SpectralDataNonnull","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"SpectralDataNonnull"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/title","value":"ISpectralData","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/fragments","value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1ISpectralData\/navigatorTitle","value":[{"text":"ISpectralData","kind":"identifier"}],"op":"replace"}]}]}