{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_LICENSE"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus"]]},"abstract":[{"text":"The device disconnected due to a problem with the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","isActive":true,"type":"reference"},{"text":". Check that the license is active via ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","type":"reference","isActive":true},{"text":" and that the device type is supported via ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_license"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_license"]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_LICENSE"}]}],"kind":"declarations"},{"kind":"mentions","mentions":["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes"]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Since 4.2.0"}]}]}],"type":"unorderedList"}]}],"metadata":{"externalID":"c:@M@NixUniversalSDK@E@DeviceStatus@DeviceStatusERROR_LICENSE","roleHeading":"Case","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"title":"DeviceStatus.ERROR_LICENSE","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ERROR_LICENSE"}],"navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_LICENSE"}],"symbolKind":"case"},"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceType":{"navigatorTitle":[{"kind":"identifier","text":"DeviceType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType","title":"DeviceType","abstract":[{"type":"text","text":"Enum to describe the supported Nix device types"}],"url":"\/documentation\/nixuniversalsdk\/devicetype","role":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"url":"\/documentation\/nixuniversalsdk","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","title":"NixUniversalSDK","type":"topic","role":"collection","kind":"symbol"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/release-notes":{"url":"\/documentation\/nixuniversalsdk\/release-notes","abstract":[{"text":"Review the changes made in this version of the library","type":"text"}],"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/release-notes","title":"Release Notes","type":"topic","role":"article","kind":"article"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","navigatorTitle":[{"kind":"identifier","text":"DeviceStateDelegate"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Definition for a callback from an "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat","isActive":true,"type":"reference"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStateDelegate"}],"title":"DeviceStateDelegate","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManagerState/ACTIVE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","type":"topic","title":"LicenseManagerState.ACTIVE","abstract":[{"type":"text","text":"The license has activated successfully and Nix Universal SDK functions are available."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ACTIVE"}],"role":"symbol","navigatorTitle":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"url":"\/documentation\/nixuniversalsdk\/licensemanagerstate\/active"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseManager"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseManager"}],"title":"LicenseManager","url":"\/documentation\/nixuniversalsdk\/licensemanager","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Class used to manage the license for the Nix Universal SDK. Members of this class are not instantiated or accessed directly. Access to a single shared instance is provided via static methods and properties."}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_LICENSE":{"url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_license","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_LICENSE","role":"symbol","title":"DeviceStatus.ERROR_LICENSE","abstract":[{"type":"text","text":"The device disconnected due to a problem with the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager"},{"text":". Check that the license is active via ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","type":"reference","isActive":true},{"type":"text","text":" and that the device type is supported via "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","type":"reference","isActive":true},{"type":"text","text":"."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ERROR_LICENSE","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_LICENSE"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/state":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LicenseManagerState","preciseIdentifier":"c:@M@NixUniversalSDK@E@LicenseManagerState","kind":"typeIdentifier"}],"title":"state","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/state","navigatorTitle":[{"text":"state","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes the current state of the  "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager","type":"reference","isActive":true},{"text":". Nix Universal SDK functions are available only if license is active (i.e. - the state is ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManagerState\/ACTIVE","type":"reference"},{"text":")","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/state"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"url":"\/documentation\/nixuniversalsdk\/devicestatus","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","role":"symbol","title":"DeviceStatus","abstract":[{"text":"Enum describing the possible causes of a device disconnection event in the ","type":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceStatus","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DeviceStatus","kind":"identifier"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/LicenseManager/isDeviceTypeSupported(_:)":{"navigatorTitle":[{"kind":"text","text":"+ "},{"text":"isDeviceTypeSupported:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isDeviceTypeSupported","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DeviceType","text":"DeviceType"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/LicenseManager\/isDeviceTypeSupported(_:)","title":"isDeviceTypeSupported(_:)","abstract":[{"type":"text","text":"Helper to check if a particular "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceType"},{"text":" is supported by the current license.","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/licensemanager\/isdevicetypesupported(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DeviceStatusERROR_LICENSE"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DeviceStatusERROR_LICENSE","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DeviceStatusERROR_LICENSE"}],"platforms":["macOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/title","op":"replace","value":"DeviceType"},{"op":"replace","value":[{"kind":"identifier","text":"DeviceType"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/fragments"},{"op":"replace","value":[{"text":"DeviceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceType\/navigatorTitle"},{"value":"DeviceStateDelegate","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","value":[{"kind":"identifier","text":"DeviceStateDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"text":"DeviceStateDelegate","kind":"identifier"}],"op":"replace"},{"value":"LicenseManagerStateACTIVE","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/title"},{"value":[{"text":"LicenseManagerStateACTIVE","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManagerState~1ACTIVE\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/title","value":"LicenseManager"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/fragments","value":[{"text":"LicenseManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager\/navigatorTitle","value":[{"text":"LicenseManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_LICENSE\/title","value":"DeviceStatusERROR_LICENSE"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_LICENSE\/fragments","value":[{"text":"DeviceStatusERROR_LICENSE","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/title","op":"replace","value":"state"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1state\/fragments","op":"replace","value":[{"text":"state","kind":"identifier"}]},{"value":"DeviceStatus","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title"},{"value":[{"kind":"identifier","text":"DeviceStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments"},{"op":"replace","value":[{"text":"DeviceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/title","value":"isDeviceTypeSupported:","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1LicenseManager~1isDeviceTypeSupported(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"isDeviceTypeSupported:","kind":"identifier"}]}]}]}