{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_INTERNAL"},"metadata":{"role":"symbol","title":"DeviceStatus.ERROR_INTERNAL","symbolKind":"case","modules":[{"name":"NixUniversalSDK"}],"roleHeading":"Case","externalID":"c:@M@NixUniversalSDK@E@DeviceStatus@DeviceStatusERROR_INTERNAL","navigatorTitle":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ERROR_INTERNAL","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"ERROR_INTERNAL","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"The device has disconnected for an unknown reason (internal SDK error).","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus"]]},"variants":[{"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_internal"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/nixuniversalsdk\/devicestatus\/error_internal"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStateDelegate":{"url":"\/documentation\/nixuniversalsdk\/devicestatedelegate","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","abstract":[{"text":"Definition for a callback from an ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/IDeviceCompat"},{"text":" instance on a connection state change, battery state change, or external power state change.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DeviceStateDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceStateDelegate","kind":"identifier"}],"title":"DeviceStateDelegate"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus/ERROR_INTERNAL":{"navigatorTitle":[{"text":"DeviceStatusERROR_INTERNAL","kind":"identifier"}],"title":"DeviceStatus.ERROR_INTERNAL","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus\/ERROR_INTERNAL","url":"\/documentation\/nixuniversalsdk\/devicestatus\/error_internal","abstract":[{"text":"The device has disconnected for an unknown reason (internal SDK error).","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ERROR_INTERNAL"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DeviceStatus":{"url":"\/documentation\/nixuniversalsdk\/devicestatus","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStatus","abstract":[{"type":"text","text":"Enum describing the possible causes of a device disconnection event in the "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DeviceStateDelegate","isActive":true,"type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DeviceStatus","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceStatus","kind":"identifier"}],"title":"DeviceStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DeviceStatusERROR_INTERNAL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/title","value":"DeviceStateDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/fragments","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStateDelegate\/navigatorTitle","value":[{"text":"DeviceStateDelegate","kind":"identifier"}]},{"value":"DeviceStatusERROR_INTERNAL","op":"replace","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_INTERNAL\/title"},{"value":[{"kind":"identifier","text":"DeviceStatusERROR_INTERNAL"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus~1ERROR_INTERNAL\/fragments","op":"replace"},{"value":"DeviceStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DeviceStatus"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DeviceStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DeviceStatus"}]}]}]}