{"abstract":[{"type":"text","text":"Helper to find a "},{"isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","type":"reference"},{"type":"text","text":" enum from an "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value, or "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE"},{"type":"text","text":" for invalid input."}],"hierarchy":{"paths":[["doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Type Method","title":"fromInt(_:)","symbolKind":"method","externalID":"s:15NixUniversalSDK13DensityStatusO7fromIntyACSiSgFZ","role":"symbol","modules":[{"name":"NixUniversalSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromInt"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"DensityStatus","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}]},"identifier":{"url":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromInt(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromInt"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":"?) -> ","kind":"text"},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/nixuniversalsdk\/densitystatus\/fromint(_:)"]}],"references":{"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","title":"DensityStatus","navigatorTitle":[{"text":"DensityStatus","kind":"identifier"}],"abstract":[{"text":"Enum to describe the available options for density status","type":"text"}],"type":"topic","url":"\/documentation\/nixuniversalsdk\/densitystatus","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DensityStatus"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK":{"title":"NixUniversalSDK","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"A library to allow integration of Nix devices into third-party iOS and macOS applications."}],"url":"\/documentation\/nixuniversalsdk"},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/NONE":{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE","type":"topic","title":"DensityStatus.NONE","abstract":[{"text":"Unknown \/ undefined conditions","type":"text"}],"url":"\/documentation\/nixuniversalsdk\/densitystatus\/none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"NONE","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DensityStatusNONE"}]},"doc://com.nixsensor.universalsdk/documentation/NixUniversalSDK/DensityStatus/fromInt(_:)":{"title":"fromInt(_:)","type":"topic","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/fromInt(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Helper to find a "},{"identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus","isActive":true,"type":"reference"},{"text":" enum from an ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value, or ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.nixsensor.universalsdk\/documentation\/NixUniversalSDK\/DensityStatus\/NONE"},{"type":"text","text":" for invalid input."}],"url":"\/documentation\/nixuniversalsdk\/densitystatus\/fromint(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fromInt"},{"text":"(","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"DensityStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@NixUniversalSDK@E@DensityStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DensityStatus","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/fragments","value":[{"text":"DensityStatus","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DensityStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus\/navigatorTitle","op":"replace"},{"op":"replace","value":"DensityStatusNONE","path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1NONE\/title"},{"path":"\/references\/doc:~1~1com.nixsensor.universalsdk~1documentation~1NixUniversalSDK~1DensityStatus~1NONE\/fragments","op":"replace","value":[{"kind":"identifier","text":"DensityStatusNONE"}]}]}]}